<a href="https://colab.research.google.com/github/Angy-face/Esan-Coding-SS2/blob/main/2_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


<img src = 'https://drive.google.com/uc?id=1prj-mqSRBDZ6j01TFDJGwcDniB-gqVE4' alt = 'image test' width ='1100px'>




บรรยายโดย <font color='blue'>ผู้ช่วยศาสตราจารย์ ดร.บุรัสกร นันทดิลก</font>

สาขาวิชา *Industrial Optimisation and Applications* (international program) และสาขาวิชา *คณิตศาสตร์*

คณะวิทยาศาสตร์ มหาวิทยาลัยแม่โจ้ จ.เชียงใหม่

คอร์สที่ 2 **Coding for Data scientists** ประกอบด้วย

2.1 <font color='darkpurple'>**Numpy**</font>

2.2 <font color='darkpurple'>Pandas</font>

2.3 <font color='darkpurple'>Matplotlib</font>

2.4 <font color='darkpurple'>Seaborn</font>

#**<font color='darkpurple'>2.1 Numpy**</font>

> **NumPy** เป็นไลบรารีของ Python ที่ให้โครงสร้างข้อมูลที่เรียบง่ายแต่ทรงพลัง นั่นคือ ใช้จัดการข้อมูล อาร์เรย์ n มิติ ได้

> การเรียนรู้ NumPy จะเป็นก้าวแรกในการเดินทางของนักวิทยาศาสตร์ข้อมูล (Python data scientist)

- Array
- Array Shapes and Axes
- Data Science Operations: Filter, Order, Aggregate

##<font color='blue'>2.1.1 Array</font>

> Array (อาเรย์) คือประเภทข้อมูลที่สามารถเก็บเรียงกันเป็นลำดับได้ หรือข้อมูลที่ระบุตำแหน่งได้

> อาจจะเรียงกันเป็นแถวแนวนอน เรียงกันเป็นเป็นแถวแนวตั้ง หรือเรียงกันเป็นตาราง หรือหลายๆตารางซ้อนกัน

<img src = 'https://drive.google.com/uc?id=1TBTrhNr7vb5Lkq9Z_mgt0x0FYRIeu7b-' alt = 'image test' width ='500px'>

In [ ]:
import numpy as np #เรียกใช้งาน numpy และแทนด้วย np

In [ ]:
number1D = np.array([1,2,3]) #ข้อมูลเรียงกันเป็นแถว (แนวนอน) ขนาด 1 แถว x 3 หลัก

In [ ]:
number1D

array([1, 2, 3])

In [ ]:
number1D[2]

3

In [ ]:
number2D = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]]) #ข้อมูลเรียงกันเป็นตารางขนาด 3 แถว x 3 หลัก

In [ ]:
number2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
number2D[(2,1)]

8

In [ ]:
number2D_2 = np.array([[1,2,3,4,5],
                       [6,7,8,9,0]])
number2D_2

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [ ]:
#สร้างตัวแปร text1 เพื่อเก็บข้อมูลตัวอักษร a, b, c ในแนวนอน
text1 = np.array(['a', 'b', 'c'])

In [ ]:
text1

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
#สร้างตัวแปร text2 เพื่อเก็บข้อมูลตัวอักษร d, e, f ในแนวตั้ง
text2 = np.array([['d'],['e'],['f']])

In [ ]:
text2

array([['d'],
       ['e'],
       ['f']], dtype='<U1')

In [ ]:
#ทดลองสร้างข้อมูล 3 มิติง่ายๆกันขนาด 2x3x4 กัน
# 2 ชั้น x 3 แถว x 4 หลัก
number3D = np.array([[[1, 2, 3, 4],
                      [11, 12, 13, 14],
                      [21, 22, 23, 24]],
                     [[34, 35, 36, 37],
                      [45, 46, 47, 48],
                      [56, 57, 58, 59]]])

In [ ]:
number3D

array([[[ 1,  2,  3,  4],
        [11, 12, 13, 14],
        [21, 22, 23, 24]],

       [[34, 35, 36, 37],
        [45, 46, 47, 48],
        [56, 57, 58, 59]]])

In [ ]:
number3D[(0,2,1)] # ทายซิ...ว่าเลขอะไร ??

22

[<font color='red'>**แบบฝึกหัด**</font>] จงสร้างอาเรย์ 2 มิติ เพื่อเก็บข้อมูลของวันที่ 1 และ 2 ไว้ในตัวแปร N1 และ N2 ตามลำดับ

และหาค่าเฉลี่ยของอุณหภูมิเฉลี่ยของทั้งสองวันเก็บไว้ใน N3

<img src = 'https://drive.google.com/uc?id=15NLul3WmoRXbOG8Bps0vqlcs9jLuRau3' alt = 'image test' width ='350px'>


In [ ]:
import numpy as np

In [ ]:
N1=np.array([[23.5,24.7,25.1],
             [35.2,34.1,32.9]])

In [ ]:
print(N1)

[[23.5 24.7 25.1]
 [35.2 34.1 32.9]]


In [ ]:
N2 = np.array([[ 22.4, 24.3, 24.9],
              [37.1, 35.5, 34.6]])

In [ ]:
N3= (N1+N2)/2

In [ ]:
N3

array([[22.95, 24.5 , 25.  ],
       [36.15, 34.8 , 33.75]])

### ตัวอย่างการใช้งานอาเรย์ ในการปรับคะแนน

> การปรับคะแนน :สมมุติว่าคะแนนที่นักศึกษาได้ อาจจะน้อยกว่าที่คาดไว้ เพราะข้อสอบอาจจะยากเกินไป

> อาจารย์จะสามารถปรับเกรดง่ายๆได้ดังตัวอย่าง (คะแนนเต็ม = 100)



In [ ]:
import numpy as np

In [ ]:
scores = np.array([71, 36, 63, 87, 49, 74, 10])

In [ ]:
np.mean(scores) #คำนวณคะแนนเฉลี่ย

55.714285714285715

In [ ]:
CURVE_CENTER = 80 #ค่าที่ใช้ปรับค่าเฉลี่ย

In [ ]:
def adjust(scores):
  average = scores.mean()
  print('Average =', average)
  change = CURVE_CENTER - average
  print('Change =', change)
  new_scores = scores + change
  print('New scores=',new_scores)
  return np.clip(new_scores, scores, 100)

In [ ]:
adjust(scores)

Average = 55.714285714285715
Change = 24.285714285714285
New scores= [ 95.28571429  60.28571429  87.28571429 111.28571429  73.28571429
  98.28571429  34.28571429]


array([ 95.28571429,  60.28571429,  87.28571429, 100.        ,
        73.28571429,  98.28571429,  34.28571429])

##<font color='blue'>2.1.2 Array Shapes and Axes</font>


> อาร์เรย์ทั้งหมดมีคุณสมบัติที่เรียกว่า .shape ซึ่งส่งกลับค่าเป็นขนาดในแต่ละมิติ

> มิติของข้อมูลเป็นเท่าไร ไม่ใช่สิ่งสำคัญ  แต่สิ่งที่สำคัญจริงๆ คืออาร์เรย์ที่คุณส่งไปยังฟังก์ชันจะต้องมีรูปร่างตามที่ฟังก์ชันคาดหวัง

> วิธีทั่วไปในการยืนยันว่าข้อมูลมีรูปร่างที่เหมาะสมคือ การพิมพ์ข้อมูลและรูปร่างจนกว่าจะแน่ใจว่า ทุกอย่างทำงานได้ตามที่คาดหวัง

###1.) Shapes

> shape (รูปร่าง) บอกจำนวนชั้น/แถว/หลัก


<img src = 'https://drive.google.com/uc?id=1xKFEWL2SodhfYKONCqCmKP10qmGYQn--' alt = 'image test' width ='550px'>

In [ ]:
import numpy as np

In [ ]:
a1 = np.array([1, 2, 3, 4]) # 1d-array

In [ ]:
a1.shape

(4,)

In [ ]:
a2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8]]) # 2d-array

In [ ]:
a2.shape

(2, 4)

In [ ]:
a3 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8]],
               [[1, 2, 3, 4],
                [5, 6, 7, 8]],
               [[1, 2, 3, 4],
                [5, 6, 7, 8]]]) # 3d-array

In [ ]:
a3.shape

(3, 2, 4)

In [ ]:
temperatures = np.array([29.3, 42.1, 18.8, 16.1, 38.1, 12.0, 12.5, 48.7, 39.9, 33.1, 9.9, 22.3]).reshape(2,2,3)

In [ ]:
temperatures.shape
print(temperatures)

[[[29.3 42.1 18.8]
  [16.1 38.1 12. ]]

 [[12.5 48.7 39.9]
  [33.1  9.9 22.3]]]


In [ ]:
temperatures #3d-array

array([[[29.3, 42.1, 18.8],
        [16.1, 38.1, 12. ]],

       [[12.5, 48.7, 39.9],
        [33.1,  9.9, 22.3]]])

In [ ]:
np.swapaxes(temperatures, 1, 2) #สลับระหว่าง แถว กับ หลัก

array([[[29.3, 16.1],
        [42.1, 38.1],
        [18.8, 12. ]],

       [[12.5, 33.1],
        [48.7,  9.9],
        [39.9, 22.3]]])

In [ ]:
np.swapaxes(temperatures, 0, 2) #สลับระหว่าง แถว กับ หลัก

array([[[29.3, 12.5],
        [16.1, 33.1]],

       [[42.1, 48.7],
        [38.1,  9.9]],

       [[18.8, 39.9],
        [12. , 22.3]]])

In [ ]:
temperatures

array([[[29.3, 42.1, 18.8],
        [16.1, 38.1, 12. ]],

       [[12.5, 48.7, 39.9],
        [33.1,  9.9, 22.3]]])

<font color='red'>16.1 เดิมอยู่ที่ตำแหน่ง (0,1,0) ย้ายไปอยู่ที่ตำแหน่ง (0,0,1)</font>

<font color='red'>39.9 เดิมอยู่ที่ตำแหน่ง (1,0,2) ย้ายไปอยู่ที่ตำแหน่ง (1,2,0)</font>


In [ ]:
np.swapaxes(temperatures, 0, 1) #สลับระหว่าง ชั้น กับ แถว

array([[[29.3, 42.1, 18.8],
        [12.5, 48.7, 39.9]],

       [[16.1, 38.1, 12. ],
        [33.1,  9.9, 22.3]]])

<font color='red'>16.1 เดิมอยู่ที่ตำแหน่ง (0,1,0) ย้ายไปอยู่ที่ตำแหน่ง (1,0,0)</font>

<font color='red'>39.9 เดิมอยู่ที่ตำแหน่ง (1,0,2) ย้ายไปอยู่ที่ตำแหน่ง (0,1,2)</font>

###2.) Axes
> axis (แกน)

<img src = 'https://drive.google.com/uc?id=1xKFEWL2SodhfYKONCqCmKP10qmGYQn--' alt = 'image test' width ='550px'>

In [ ]:
import numpy as np

In [ ]:
table1 =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]).reshape(4,4)

In [ ]:
table1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
print(table1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
table1.max()

16

In [ ]:
table1.max(axis=0)

array([13, 14, 15, 16])

In [ ]:
table1.max(axis=1)

array([ 4,  8, 12, 16])

In [ ]:
table2 =np.array([1, 2, 13, 14, 5, 6, 7, 8, 9, 10, 11, 12, 3, 4, 15, 16]).reshape(4,2,2)

In [ ]:
table2

array([[[ 1,  2],
        [13, 14]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[ 3,  4],
        [15, 16]]])

In [ ]:
table2.max(axis=0)

array([[ 9, 10],
       [15, 16]])

In [ ]:
table2.max(axis=1)

array([[13, 14],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [ ]:
table2.max(axis=2)

array([[ 2, 14],
       [ 6,  8],
       [10, 12],
       [ 4, 16]])

[<font color='red'>**แบบฝึกหัด**</font>] จงสร้างอาเรย์ 3 มิติ ขนาด (2,3,2) เพื่อเก็บข้อมูล 1 - 12 ไว้ในตัวแปร num3d

และหาค่า min เมื่อ axis = 1

In [ ]:
import numpy as np

In [ ]:
num3d = np.array([3, 4, 1, 10, 23, 41, 77, 24, 51, 73, 5, 99]).reshape(2,3,2)

In [ ]:
num3d

array([[[ 3,  4],
        [ 1, 10],
        [23, 41]],

       [[77, 24],
        [51, 73],
        [ 5, 99]]])

In [ ]:
num3d.min(axis= 1)

array([[ 1,  4],
       [ 5, 24]])

##<font color='blue'>2.1.3 Data Science Operations: Filter, Order, Aggregate</font>

> กรองข้อมูล, จัดเรียงข้อมูล, การนำข้อมูลมาต่อกัน

###1.) Masking

> การกรองข้อมูลโดยใช้ mask

> **mask** คือ อาเรย์ที่มีขนาดเท่ากันกับขนาดข้อมูลของเรา แต่ไม่ใช้อาเรย์ที่เก็บข้อมูล เป็นอาเรย์ที่เก็บค่า True หรือ False

เราสามารถใช้ mask เพื่อเป็น index ของข้อมูลได้ ซึ่ง*จะได้ค่าข้อมูลที่เป็น True ออกมา*


In [ ]:
import numpy as np

In [ ]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [ ]:
np.linspace(0, 10, 25, dtype = int)

array([ 0,  0,  0,  1,  1,  2,  2,  2,  3,  3,  4,  4,  5,  5,  5,  6,  6,
        7,  7,  7,  8,  8,  9,  9, 10])

In [ ]:
numbers = np.linspace(5, 50 ,25, dtype = int).reshape(5,-1) #Reshaping an array with -1 โปรแกรมคำนวณหลักเอาเองด้วย -1

In [ ]:
numbers

array([[ 5,  6,  8, 10, 12],
       [14, 16, 18, 20, 21],
       [23, 25, 27, 29, 31],
       [33, 35, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [ ]:
mask = numbers % 5 == 0 #modulo

In [ ]:
mask

array([[ True, False, False,  True, False],
       [False, False, False,  True, False],
       [False,  True, False, False, False],
       [False,  True, False, False,  True],
       [False, False, False, False,  True]])

In [ ]:
numbers[mask] #เอาเฉพาะตัวที่เป็น True

array([ 5, 10, 20, 25, 35, 40, 50])

In [ ]:
by_five = numbers[numbers % 5 == 0]

In [ ]:
by_five

array([ 5, 10, 20, 25, 35, 40, 50])

In [ ]:
by_five.shape #.shape บอกลักษะmetrix ว่ามีกี่ตัว หลัก แถว

(7,)

###2.) Transposing

> การจัดเรียงข้อมูลโดยสลับแถวและหลัก

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
a.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

###3.) Sorting

> การจัดเรียงข้อมูลโดยเรียงลำดับข้อมูลจากน้อยไปหามาก

In [ ]:
import numpy as np

In [ ]:
data = np.array([[3, 1, 5],
                 [5, 7, 6],
                 [1, 8, 9]])

In [ ]:
data

array([[3, 1, 5],
       [5, 7, 6],
       [1, 8, 9]])

In [ ]:
np.sort(data)

array([[1, 3, 5],
       [5, 6, 7],
       [1, 8, 9]])

In [ ]:
data

array([[3, 1, 5],
       [5, 7, 6],
       [1, 8, 9]])

In [ ]:
np.sort(data, axis = None)

array([1, 1, 3, 5, 5, 6, 7, 8, 9])

In [ ]:
np.sort(data, axis = 0)

array([[1, 1, 5],
       [3, 7, 6],
       [5, 8, 9]])

###4.) Concatenating

> การรวมข้อมูล หรือเอาข้อมูลมาต่อกัน

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2],
              [6, 7]])

In [ ]:
b = np.array([[3, 5],
              [8, 9]])

In [ ]:
np.hstack((a, b))

array([[1, 2, 3, 5],
       [6, 7, 8, 9]])

In [ ]:
np.vstack((a, b))

array([[1, 2],
       [6, 7],
       [3, 5],
       [8, 9]])

In [ ]:
np.vstack((b, a))

array([[3, 5],
       [8, 9],
       [1, 2],
       [6, 7]])

In [ ]:
np.concatenate((a, b))

array([[1, 2],
       [6, 7],
       [3, 5],
       [8, 9]])

In [ ]:
np.concatenate((a, b), axis = None)

array([1, 2, 6, 7, 3, 5, 8, 9])

[<font color='red'>**แบบฝึกหัด**</font>] จากภาพ จงนำข้อมูลของทั้ง 4 คน มาต่อกันและเรียงข้อมูลให้ถูกต้องตามเวลา

เมื่อกำหนดอาเรย์ T1, T2, T3, และ T4  แทนข้อมูลของคนที่ 1, 2, 3, และ 4 ตามลำดับ

<img src = 'https://drive.google.com/uc?id=1xxgkT7ctMkyivPRLbxzfA7HiDXzSLr-1' alt = 'image test' width ='550px'>

In [ ]:
import numpy as np

In [ ]:
T1 = np.array([20.15, 23.22])
T2 = np.array([32.12, 32.85])
T3 = np.array([27.55, 30.05])
T4 = np.array([34.43, 33.68])

In [ ]:
TT = np.sort(np.concatenate((T1, T2, T3, T4), axis = None))

In [ ]:
TT

array([20.15, 23.22, 27.55, 30.05, 32.12, 32.85, 33.68, 34.43])

#**เอกสารอ้างอิง**

> https://www.programiz.com/python-programming/operators

> https://realpython.com/numpy-tutorial/

> https://www.geeksforgeeks.org/numpy-tutorial/

> https://www.w3schools.com/python/numpy/default.asp

> หรือค้นหาในเว็บเบราว์เซอร์ ด้วยคำว่า "Data Science, Numpy"

<img src = 'https://drive.google.com/uc?id=1yV9MzBC4w8J58eKhK8iCuo_O7ttjo4tQ' alt = 'image test' width ='1100px'>