<a href="https://colab.research.google.com/github/Angy-face/Esan-Coding-SS2/blob/main/3_4_Supervised_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src = 'https://drive.google.com/uc?id=18zsxFId1FaUI1RvfkAex6ZoNpToP8GoT'>

# ผู้เรียบเรียงเนื้อหา: ดร.เปรม จันทร์สว่าง
## สาขาวิชาสถิติ คณะวิทยาศาตร์ มหาวิทยาลัยขอนแก่น

# ผู้บรรยาย: ดร.วิธวินท์ สุสุทธิ
## ภาควิชาคณิตศาสตร์ คณะวิทยาศาสตร์ มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี

## **การเรียนรู้แบบมีผู้สอน (Supervised learning)**
- แนวคิดการเรียนรู้แบบมีผู้สอน
- ปัญหา Overfitting และ underfitting
- ตัวอย่าง classification models และ model selection.

### **1. แนวคิดการเรียนรู้แบบมีผู้สอน (Concept of supervised learning)**

**การเรียนรู้แบบมีผู้สอน** (Supervised learning) เป็นแนวคิดการพัฒนาหรือสอนตัวแบบเพื่อให้ตัวแบบสามารถเรียนรู้รูปแบบความสัมพันธ์ระหว่างตัวแปรต้นและตัวแปรตาม ซึ่งในที่นี้ตัวแปรตามจะเรียกว่า '*ตัวแปรเป้าหมาย (Target variable)*' โดยสามารถแบ่งกลุ่มวิธีการเรียนรู้แบบมีผู้สอนออกเป็น 2 กลุ่ม ตามลักษณะของตัวแปรเป้าหมาย ดังนี้

> **ตัวแบบเชิงจำแนก** (Classification models)
ตัวแบบที่พัฒนาเพื่อเรียนรู้รูปแบบความสัมพันธ์ระหว่างตัวแปรต้นและตัวแปรเป้าหมาย (Target variable) โดยที่ตัวแปรเป้าหมายเป็นชนิดไม่ต่อเนื่องหรือตัวแปรเชิงจำแนก (Categorical variable) ค่าที่เป็นไปได้ของตัวแปรเป้าหมายจะเรียกว่า ป้ายระบุกลุ่ม (Class labels) ถ้าค่าที่เป็นไปได้ของตัวแปรเป้าหมาย มี 2 ประเภท จะเรียกว่า ตัวแปรเชิงจำแนกแบบสองกลุ่ม (Binary classification models) และถ้าค่าที่เป็นไปได้ของตัวแปรเป้าหมาย มีมากกว่า 2 ประเภท จะเรียกว่า ตัวแปรเชิงจำแนกแบบหลายกลุ่ม (Multiclass classification models) เช่นตัวแบบจำแนกผู้ป่วยโรคเบาหวาน (ป้ายระบุกลุ่มคือ เป็นโรค หรือไม่เป็นโรค) ตัวแบบจำแนกอีเมลสแปม (ป้ายระบุกลุ่มคือ อีเมลสแปม หรืออีเมลปกติ) ตัวแบบจำแนกตัวอักษร (ป้ายระบุกลุ่มคือ A, B, C, D,..., Z) เป็นต้น     

> **ตัวแบบเชิงถดถอย** (Regression model) ตัวแบบที่พัฒนาเพื่อเรียนรู้รูปแบบความสัมพันธ์ระหว่างตัวแปรต้นและตัวแปรเป้าหมาย (Target variable) โดยที่ตัวแปรเป้าหมายเป็นชนิดต่อเนื่อง ตัวอย่างเช่นตัวแบบพยากรณ์ปริมาณน้ำฝนจากข้อมูลสภาพภูมิอากาศ หรือตัวแบบทำนายค่า pm 2.5 ล่วงหน้าหนึ่งสัปดาห์ เป็นต้น


<img src = 'https://drive.google.com/uc?id=1gnh2BvVirXMy4g-UnQpIhAOElaxLZxi-' alt = 'Supervised learning' width ='550px' height = '700px'>



ตัวอย่างข้อมูลสำหรับการพัฒนาตัวแบบการเรียนรู้แบบมีผู้สอน

<img src = 'https://drive.google.com/uc?id=1CAphL7sie0nlH7OkZFVREdRLbbiPk5sM' alt = 'Supervised learning' width ='400px' height = '400px'>

### **2. ปัญหา Overfitting และ underfitting**
 ปัญหาที่มักพบในการพัฒนาตัวแบบการเรียนรู้ของเครื่องคือปัญหา Overfitting และปัญหา Underfitting

#### **ปัญหา Overfitting** คือการที่ตัวแบบสามารถเรียนรู้รูปแบบข้อมูลได้ดีในข้อมูลชุดสอนแต่ไม่สามารถจำแนกข้อมูลในข้อมูลชุดทดสอบ กล่าวคือตัวแบบทำงานได้ดีเฉพาะข้อมูลที่ใช้ในการสอนหรือจดจำข้อมูลในชุดสอนมากเกินไปจนไม่สามารถจำแนกข้อมูลในชุดทดสอบได้

<img src = 'https://drive.google.com/uc?id=1BMSAY62Q6WOFOxn3W5LPTe-ewa7H90xb' alt = 'ML workflow' width ='700px' height = '500px'>  

#### **ปัญหา Underfitting** คือการที่ตัวแบบไม่สามารถเรียนรู้รูปแบบข้อมูลได้ดีทั้งในข้อมูลชุดสอนและในข้อมูลชุดทดสอบ

<img src = 'https://drive.google.com/uc?id=1dqb8vC-SEeEeB01raO1dLn87gUCPcJhH' alt = 'ML workflow' width ='700px' height = '500px'>

#### **อ้างอิง**

[ref1](https://www.simplilearn.com/tutorials/machine-learning-tutorial/overfitting-and-underfitting)

[ref2](https://towardsdatascience.com/overfitting-and-underfitting-principles-ea8964d9c45c)

### **3.ตัวอย่างการพัฒนาตัวแบบเชิงจำแนกและการเลือกตัวแบบ**
ตัวอย่างนี้จะเป็นการสร้างตัวแบบเชิงจำแนกเพื่อจำแนกรูปภาพตัวเลข 0-9 โดยมีขั้นตอนดังนี้

ขั้นตอนที่ 1. ดึงข้อมูลรูป

ขั้นตอนที่ 2. สำรวจข้อมูลรูป

ขั้นตอนที่ 3. เตรียมข้อมูล

ขั้นตอนที่ 4. พัฒนาและตรวจสอบตัวแบบ

ขั้นตอนที่ 5. ประเมินตัวแบบ

**ขั้นตอนที่ 1 ดึงข้อมูล**

In [ ]:
from sklearn.datasets import load_digits
dat_digits = load_digits()

**ขั้นตอนที่ 2 สำรวจข้อมูล**

In [ ]:

print(f'Keys: {dat_digits.keys()}')

Keys: dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])


In [ ]:
print(dat_digits.DESCR)

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 1797
:Number of Attributes: 64
:Attribute Information: 8x8 image of integer pixels in the range 0..16.
:Missing Attribute Values: None
:Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
:Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each block. This generates
an in

In [ ]:
dat_digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
dat_digits.data.shape

(1797, 64)

In [ ]:
dat_digits.images[10]

array([[ 0.,  0.,  1.,  9., 15., 11.,  0.,  0.],
       [ 0.,  0., 11., 16.,  8., 14.,  6.,  0.],
       [ 0.,  2., 16., 10.,  0.,  9.,  9.,  0.],
       [ 0.,  1., 16.,  4.,  0.,  8.,  8.,  0.],
       [ 0.,  4., 16.,  4.,  0.,  8.,  8.,  0.],
       [ 0.,  1., 16.,  5.,  1., 11.,  3.,  0.],
       [ 0.,  0., 12., 12., 10., 10.,  0.,  0.],
       [ 0.,  0.,  1., 10., 13.,  3.,  0.,  0.]])

In [ ]:
dat_digits.data[10,:]

array([ 0.,  0.,  1.,  9., 15., 11.,  0.,  0.,  0.,  0., 11., 16.,  8.,
       14.,  6.,  0.,  0.,  2., 16., 10.,  0.,  9.,  9.,  0.,  0.,  1.,
       16.,  4.,  0.,  8.,  8.,  0.,  0.,  4., 16.,  4.,  0.,  8.,  8.,
        0.,  0.,  1., 16.,  5.,  1., 11.,  3.,  0.,  0.,  0., 12., 12.,
       10., 10.,  0.,  0.,  0.,  0.,  1., 10., 13.,  3.,  0.,  0.])

ตัวอย่างภาพ 24 รูปแรก

<img src = 'https://drive.google.com/uc?id=1FnXl2rctdkxKOTlK67gOsGfN98mdF_AQ' alt = 'ML workflow' width ='700px' height = '500px'>

**ขั้นตอนที่ 3 เตรียมข้อมูล**
ขั้นตอนนี้จะเป็นการแบ่งข้อมูลเพื่อสอนตัวแบบ ตรวจสอบตัวแบบ และทดสอบตัวแบบ

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dat_digits.data, dat_digits.target, test_size = 0.2, random_state=40)

In [ ]:
X_train1, X_valid, y_train1, y_valid = train_test_split(X_train, y_train, test_size = 0.1, random_state=40)

**ขั้นตอนที่ 4 พัฒนาและตรวจสอบตัวแบบ**

In [ ]:
knn_n = [1,3,5]

from sklearn.neighbors import KNeighborsClassifier

knn_acc = [0]*len(knn_n)
for i in range(3):
  knn = KNeighborsClassifier(n_neighbors = knn_n[i])
  knn.fit(X_train1, y_train1)
  knn_acc[i] = knn.score(X_valid, y_valid)

In [ ]:
dt_cri = ['gini','entropy', 'log_loss']
from sklearn.tree import DecisionTreeClassifier
dt_acc = [0]*len(knn_n)
for i in range(3):
  dt = DecisionTreeClassifier(criterion =dt_cri[i], random_state=0)
  dt.fit(X_train1, y_train1)
  dt_acc[i] = dt.score(X_valid, y_valid)

**ขั้นตอนที่ 5 ประเมินตัวแบบ**

In [ ]:
import numpy as np
best_knn = np.argmax(knn_acc)
best_dt = np.argmax(dt_acc)
print('Performance on validation dataset')
print(f'Best k of KNN: {knn_n[best_knn]} / Acc = {knn_acc[best_knn]:.2f}')
print(f'Best criterion of DT: {dt_cri[best_dt]} / Acc = {dt_acc[best_dt]:.2f}')

Performance on validation dataset
Best k of KNN: 1 / Acc = 0.98
Best criterion of DT: entropy / Acc = 0.88


In [ ]:
knn_best = KNeighborsClassifier(n_neighbors = 1)
knn_best.fit(X_train,y_train)
dt_best = DecisionTreeClassifier(criterion = 'entropy', random_state=0)
dt_best.fit(X_train,y_train)
acc_knn_best = knn_best.score(X_test,y_test)
acc_dt_best = dt_best.score(X_test,y_test)
print('Acc on test dataset:')
print(f'Best acc of KNN = {acc_knn_best:.2f}')
print(f'Best acc of DT = {acc_dt_best:.2f}')

Acc on test dataset:
Best acc of KNN = 0.99
Best acc of DT = 0.87


<img src = 'https://drive.google.com/uc?id=18qUXmnQK3FIPfMCm8m0aKf1Saam6ezdJ'>
<img src = 'https://drive.google.com/uc?id=192V5NZG8GXDFzYQIxTRJCSmiBUkc2xys'>