<a href="https://colab.research.google.com/github/Angy-face/Esan-Coding-SS2/blob/main/Course2Topic1Part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src = 'https://drive.google.com/uc?id=18zsxFId1FaUI1RvfkAex6ZoNpToP8GoT'>

---

# ผู้บรรยาย: ผู้ช่วยศาสตราจารย์ ดร. วีระชัย สาระคร
## สาขาวิชาคณิตศาสตร์ คณะวิทยาศาสตร์ มหาวิทยาลัยขอนแก่น

---

# Topic 1: Basic Python Programming for Data Scientists

# 1.5 การเรียกใช้งานชุดคำสั่งหรือไลบรารีต่างๆ
ในภาษาไพทอน ชุดคำสั่งที่เป็นจำเป็นที่สร้างขึ้นสำหรับนำไปใช้ในการคำนวณหรือแก้ปัญหาเฉพาะทางโดยนักพัฒนาได้เก็บไว้ในมอดูล(Modules)และไลบรารี(Libraries) ที่ถูกติดตั้งมาพร้อมกับภาษาไพทอน

### มอดูล (Modules)
คือไฟล์ที่ถูกเขียนขึ้นด้วยภาษาไพทอนซึ่งลงท้ายด้วยนามสกุล .py
มอดูลประกอบด้วยฟังก์ชัน คลาส และตัวแปรต่าง ๆ ที่ถูกจัดเก็บไว้เพื่อให้ผู้พัฒนาหรือนักพัฒนาทั่วไปสามารถนำไปใช้ได้

### ไลบรารี (Libraries)
คือชุดคำสั่งและฟังก์ชันที่ถูกพัฒนาขึ้นและจัดเก็บไว้เพื่อให้นักพัฒนาสามารถนำไปใช้ต่อได้
ไลบรารีเป็นชุดของมอดูลที่ถูกสร้างขึ้นเพื่อประโยชน์ในวงกว้าง

### ตัวอย่างมอดูลและไลบรารีที่จำเป็นสำหรับวิทยาการข้อมูล
1. มอดูล `math` ใช้สำหรับการคำนวณทางคณิตศาสตร์
2. มอดูล `statistics` ใช้สำหรับการคำนวณข้อมูลเชิงสถิติ
3. ไลบรารี `NumPy` ใช้สำหรับการคำนวณที่เกี่ยวกับอาร์เรย์และเมทริกซ์
4. ไลบรารี `Pandas` ใช้สำหรับการจัดการข้อมูลโครงสร้างแบบตาราง
5. ไลบรารี `Matplotlib` ใช้สำหรับการวาดกราฟและแสดงผล
6. ไลบรารี `Seaborn`  ใช้สำหรับการวาดกราฟและแสดงผล
7. ไลบรารี `Scikit-Learn` ใช้สำหรับการประยุกต์ใช้การเรียนรู้ของเครื่อง(Machine Learning: ML)
เป็นต้น

สำหรับคำสั่งพื้นฐานทั่วไป นักพัฒนาสามารถเรียกใช้งานคำสั่งนั้นได้โดยตรง ในขณะที่คำสั่งต่างๆที่เก็บไว้ในมอดูลหรือไลบรารีนั้น นักพัฒนาจะต้องสั่งการให้ภาษาไพทอนนำเข้า(import)มาก่อน แล้วค่อยเรียกใช้งานคำสั่งต่างๆภายในมอดูลหรือไลบรารีนั้นได้

### การเรียกใช้งานมอดูลหรือไลบรารี
การเรียกใช้งานงานมอดูลหรือไลบรารีสามารถใช้คำสั่งดังนี้
```
import desired_module_or_library
```
เมื่อ `desired_module_or_library` เป็นมอดูลหรือไลบรารีที่ต้องการเรียกใช้งาน นอกจากนี้ การเรียกใช้งานมอดูลหรือไลบรารีที่ต้องการแล้ว ภาษาไพทอนยังยอมให้ผู้ใช้งานตั้งชื่อไลบรารีที่เรียกใช้งานเป็นชื่อใหม่ตามที่ต้องการได้ โดยใช้คำสั่งดังนี้
```
import desired_module_or_library as new_module_or_library_name
```
เมื่อ `new_module_or_library_name`เป็นชื่อเรียกใหม่ของไลบรารี `desired_module(library)` เดิม
อย่างไรก็ตาม หากไม่ต้องการอ้างอิงชื่อมอดูลหรือไลบรารีนำหน้าคำสั่งที่อยู่ภายในมอดูลหรือไลบรารีนั้น สามารถใช้คำสั่งดังนี้
```
from desired_module_or_library import *
```

**ตัวอย่าง 1.5.1** ตัวอย่างการเรียกใช้งานมอดูล `math` คำสั่งเป็นดังนี้

In [ ]:
import math

กรณีเรียกใช้งานงานมอดูล `math` แต่ตั้งชื่อใหม่ให้เป็น `m` คำสั่งเป็นดังนี้

In [ ]:
import math as m

หรือ กรณีไม่ต้องการอ้างอิงชื่อไลบรารี `math` คำสั่งเป็นดังนี้

In [ ]:
from math import *
ceil(6.5)

7

# 1.6 มอดูลทางคณิตศาสตร์
เป็นไลบรารีที่รวบรวมชุดคำสั่งหรือฟังก์ชันต่างๆ ทางคณิตศาสตร์ ในที่นี้จะแนะนำ ฟังก์ชันเกี่ยวกับการดำเนินการเลขคณิตและค่าคงที่  ฟังก์ชันตรีโกณมิติ ฟังก์ชันไฮเพอร์โบลิก ฟังก์ชันกำลัง ฟังก์ชันเอ็กซ์โพเนนเชียล ฟังก์ชันลอการิทึมและฟังก์ชันเกี่ยวกับจำนวนเชิงซ้อน ตามลำดับ

## 1.6.1 ฟังก์ชันเกี่ยวกับการดำเนินการเลขคณิตและค่าคงที่
ชื่อคำสั่งที่สำคัญเกี่ยวกับจำนวนและค่าคงที่เป็นดังนี้ เมื่อกำหนด `x,y` เป็นตัวแปร
- `math.ceil(x)` ปัดค่าตัวเลขขึ้นให้เป็นจำนวนเต็ม (ปัดให้เป็นจำนวนที่น้อยที่สุดที่มากกว่าหรือเท่ากับ `x` สัญลักษณ์ทางคณิตศาสตร์คือ $\lceil x\rceil$)
- `math.floor` ปัดค่าตัวเลขลงให้เป็นจำนวนเต็ม (ปัดให้เป็นจำนวนเต็มที่มากที่สุดที่น้อยกว่าหรือเท่ากับ `x`  สัญลักษณ์ทางคณิตศาสตร์คือ $\lfloor x\rfloor$)
- `math.trunc(x)` ปัดค่าส่วนที่เป็นทศนิยมออก
- `math.inf` กำหนดค่าให้เป็น infinity
- `math.nan` กำหนดค่าที่ไม่ใช่จำนวน (Not A Number)
- `math.isinf(x)` ตรวจสอบว่า `x` มีค่าเป็น infinity หรือไม่
- `math.isnan(x)` ตรวจสอบว่า`x` มีค่าเป็น “Not a number” หรือไม่
- `math.abs(x)` หาค่าสัมบูรณ์ของ `x` และจัดเก็บค่าที่ได้ตามประเภทของตัวแปร `x`
- `math.fabs` หาค่าสัมบูรณ์ของ `x` และจัดเก็บค่าที่ได้เป็นจำนวนทศนิยมเสมอ
- `math.copysign(x,y)` หาค่าสัมบูรณ์ของ x แต่เครื่องหมายหน้า `x`เหมือนกับ y
- `math.pi` ให้ค่า $\pi$
- `math.e` ให้ค่าคงที่ของออยเลอร์ $e=2.718281828459045...$
- `math.sqrt(x)` หาค่ารากที่ 2 ของ `x`
เป็นต้น

## 1.6.2 ฟังก์ชันตรีโกณมิติ
ตัวอย่างของฟังก์ชันตรีโกณมิติได้แก่
- `math.sin(x)` ใช้คำนวณค่า $\sin(x)$     
- `math.cos(x)` ใช้คำนวณค่า $\cos(x)$
- `math.tan(x)` ใช้คำนวณค่า $\tan(x)$
- `math.asin(x)` ใช้คำนวณค่า $\sin^{-1}(x)$
- `math.acos(x)` ใช้คำนวณค่า $\cos^{-1}(x)$
- `math.atan(x)`  ใช้คำนวณค่า $\tan^{-1}(x)$     
- `math.degrees` ใช้แปลงค่ามุมในหน่วยเรเดียนให้เป็นองศา
- `math.radians` ใช้แปลงค่ามุมในหน่วยองศาให้เป็นเรเดียน
## 1.6.3 ฟังก์ชันไฮเพอร์โบลิก
ตัวอย่างของฟังก์ชันไฮเพอร์โบลิกได้แก่
- `math.sinh(x)` ใช้คำนวณค่า $\sinh(x)$
- `math.cosh(x)`  ใช้คำนวณค่า $\cosh(x)$
- `math.tanh(x)` ใช้คำนวณค่า $\tanh(x)$
- `math.asinh(x)` ใช้คำนวณค่า $\sinh^{-1}(x)$    
- `math.acosh(x)` ใช้คำนวณค่า $\cosh^{-1}(x)$    
- `math.atanh(x)` ใช้คำนวณค่า $\tanh^{-1}(x)$     

**หมายเหตุ:**

1) ฟังก์ชันตรีโกณมิติและไฮเพอร์โบลิกต่างๆ จะใช้ค่ามุมในหน่วยเรเดียนทั้งหมด

2) $\sinh(x)= \frac{e^{x}-e^{-x}}{2}$, $\sinh ^{-1}(x)=\ln \left(x+\sqrt{x^2+1}\right)$

3) $\cosh(x)= \frac{e^{x}+e^{-x}}{2}$, $\cosh ^{-1}(x)=\ln \left(x+\sqrt{x^2-1}\right)$

4) $\tanh(x) = \frac{e^{x}-e^{-x}}{e^{x}+e^{-x}}$, $\tanh ^{-1}(x)=\frac{1}{2} \ln \left(\frac{1+x}{1-x}\right)$

In [ ]:
log10(101)

2.0043213737826426

## 1.6.4 ฟังก์ชันกำลัง ฟังก์ชันเอ็กซ์โพเนนเชียล และฟังก์ชันลอการิทึม
ตัวอย่างฟังก์ชันเอ็กซ์โพเนนเชียลได้แก่
- `math.pow(x,y)` คำนวณค่า $x^y$
- `math.exp(x)` คำนวณค่า $e^{x}$
- `math.expm1` คำนวณค่า $e^{x}-1$
- `math.log(x)` คำนวณค่า $\ln(x)$
- `math.log1p(x)` คำนวณค่า $\ln(1+x)$
- `math.log2(x)` คำนวณค่า $\log_{2}(x)$
- `math.log10(x)` คำนวณค่า $\log_{10}(x)$


**ตัวอย่าง 1.6.1**
จงบอกคำสั่งที่ใช้ในการคำนวณนิพจน์ทางคณิตศาสตร์ต่อไปนี้เมื่อกำหนดให้ $x=3$ และ $y=-4$
1. $p=1+e^{x-2}+\left(\frac{\pi}{5}\right)^{|y-2|}$
2. $q=\sin\frac{\pi}{6}+\cos\frac{\pi}{3}+\ln(3+x)+10^{6}\log_{10}|y|$

In [ ]:
import math
x=3
y=-4
p=1+math.exp(x-2)+(math.pi/5)**math.fabs(y-2)
print(p)
q=math.sin(math.pi/6)+math.cos(math.pi/3)+math.log(3+x)+10**6*math.log10(math.fabs(y))
print(q)

3.7798107368478644
602062.7830874316


In [ ]:
p1 = 1+ exp(x-2)+(pi/5)**abs(y-2)
q1 = sin(pi/6)+cos(pi/3)+log(3+x)+10**6*log10(fabs(y))

In [ ]:
print(p1 == p , q1 ==q)

True True


**ตัวอย่าง 1.6.2** จงใช้เขียนคำสั่งในการรับค่าข้อมูล `x` ที่เป็นจำนวนจริง จากนั้น หาค่า $$y=2-\frac{x}{5}+x^2-\log_{10}(|x|)+e^{-\frac{x}{4}}$$
แล้วแสดงค่า $y$ ถึงทศนิยม $8$ ตำแหน่ง

In [ ]:
import math as m
x=float(input("Input x = "))
y=2-x/5+x**2-m.log10(m.fabs(x))+m.exp(-x/4)
print("y = {:.8f}".format(y))

Input x = 5
y = 25.58753479


In [ ]:
y1 = 2 - x/5 + x**2 - log10(fabs(x))+exp(-x/4)
(y1 == y)

True


**ตัวอย่าง 1.6.3**
จงเขียนชุดคำสั่งภาษาไพทอนเพื่อคำนวณหาความยาวของด้านที่สาม($c$)ของรูปสามเหลี่ยม เมื่อเราทราบความยาวด้านสองด้าน($a$ และ $b$) และมุมระหว่างด้านสองด้านที่กำหนดให้เป็น ($\theta$) โดยใช้กฎของโคไซน์ดังนี้
$$
c^{2}=a^{2}+b^{2}-2 a b \cos (\theta)
$$

<img src='https://drive.google.com/uc?id=16-xRcrls1ZfZaWfhO8kiP_c2OMO4iCl0' align="right" width="300"/>

เมื่อกำหนดให้ ข้อมูลเข้าจากแป้นพิมพ์คือ
  1. ความยาวด้าน $a$ หน่วยเซนติเมตร
  2. ความยาวด้าน $b$ หน่วยเซนติเมตร
  3. มุม $\theta$ (หน่วยองศา)

ข้อมูลออกทางจอภาพคือ
1. ความยาวด้านที่สาม $c$ หน่วยเซนติเมตร



In [4]:
a = float(input("a : "))
b = float(input("b : "))
theta = math.radians(float(input("theta : ")))
import math
c = math.sqrt(a**2 + b**2 - 2*a*b*math.cos(theta))
print(c)

a : 3
b : 4
theta : 53
3.2490674730375853


In [3]:
print('โปรแกรมนี้ออกแบบเพื่อใช้ในการคำนวณด้านที่สามของรูปสามเหลี่ยม')
print('เมื่อเราทราบความยาวด้านสองด้าน ในที่นี้สมมุติให้เป็น a และ b (หน่วยเซนติเมตร')
print('และขนาดของมุมระหว่างด้านสองด้านนี้ สมมุติให้เป็น theta (หน่วยองศา)')
a = float(input('ป้อนค่าความยาวด้าน a (เซนติเมตร) = '))
b = float(input('ป้อนค่าความยาวด้าน b (เซนติเมตร) = '))
theta = float(input('ป้อนค่ามุมระหว่างด้าน a และ b คือ theta (องศา) = '))
from math import *
theta=radians(theta)
c=sqrt(a**2+b**2-2*a*b*cos(theta))
print('ความยาวด้านที่สามคือ c = {:f} เซนติเมตร'.format(c))

โปรแกรมนี้ออกแบบเพื่อใช้ในการคำนวณด้านที่สามของรูปสามเหลี่ยม
เมื่อเราทราบความยาวด้านสองด้าน ในที่นี้สมมุติให้เป็น a และ b (หน่วยเซนติเมตร
และขนาดของมุมระหว่างด้านสองด้านนี้ สมมุติให้เป็น theta (หน่วยองศา)
ป้อนค่าความยาวด้าน a (เซนติเมตร) = 3
ป้อนค่าความยาวด้าน b (เซนติเมตร) = 4
ป้อนค่ามุมระหว่างด้าน a และ b คือ theta (องศา) = 53
ความยาวด้านที่สามคือ c = 3.249067 เซนติเมตร


# 1.7 ข้อมูลแบบซับซ้อน(Non-primitive): ลิสต์ อาร์เรย์และเมทริกซ์

## 1.7.1 ลิสต์
จากการที่ได้กล่าวไปแล้วว่าลิสต์ (List) เป็นโครงสร้างข้อมูลที่ซับซ้อน(non-primitive)ที่ใช้เก็บข้อมูลต่าง ๆ เป็นลำดับ(sequence) ลิสต์สามารถถูกเปลี่ยนแปลงได้ในภายหลัง(mutable) ลิสต์ใช้เครื่องหมาย `[ ]` เพื่อระบุตำแหน่งของข้อมูลในลิสต์ โดยแต่ละข้อมูลจะถูกคั่นด้วยเครื่องหมายจุลภาค `,`
### การอ้างอิงลำดับของข้อมูลในลิสต์
สำหรับค่าของข้อมูลในตัวแปรลิสต์จะมีดัชนี(index) กำกับลำดับข้อมูล ถ้าชุดข้อมูลมี $n$ ค่า  ข้อมูลลำดับตัวแรกหรือซ้ายสุดจะมีดัชนีเท่ากับ 0 ส่วนดัชนีลำดับสุดท้ายของข้อมูลจะเป็น $n-1$ หรือ -1

|    ดัชนี   | ลำดับของข้อมูล |
|:--------:|:-----------:|
|     0    |      1      |
|     1    |      2      |
|     2    |      3      |
| $\vdots$ |   $\vdots$  |
|    n-2   |     n-1     |
|  n-1 หรือ -1 |      n      |

**ตัวอย่าง 1.7.1** พิจารณาลิสต์ต่อไปนี้

In [5]:
lib=['math', 'Numpy', 'SciPy', 'matplotlib', 'pandas','Seaborn','scikit-learn']

In [6]:
print(lib[0])

math


In [7]:
print(lib[3])

matplotlib


In [8]:
print(lib[6])

scikit-learn


In [9]:
print(lib[-1])

scikit-learn


### การสร้างลิสต์ซ้อนลิสต์
ลิสต์ซ้อนลิสต์ (nested lists)คือการนำลิสต์มาซ้อนไว้ภายในลิสต์อีกชั้นหนึ่ง วัตถุประสงค์คือทำให้สามารถสร้างโครงสร้างข้อมูลที่มีลำดับหรือโครงสร้างที่ซับซ้อนได้มากขึ้น

**ตัวอย่าง 1.7.2** พิจารณาลิสต์ต่อไปนี้

In [10]:
# ลิสต์ซ้อนลิสต์ของตัวเลข
nestlist1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# ลิสต์ซ้อนลิสต์ของสตริง
nestlist2 = [['apple', 'orange'], ['banana', 'grape'], ['cherry', 'kiwi']]

# ลิสต์ซ้อนลิสต์ของประเภทข้อมูลต่าง ๆ
nestlist3 = [[1, 'one', 2.0], ['apple', 'orange', 'banana'], [True, False, True]]

# ลิสต์ซ้อนลิสต์ที่ภายในลิสต์มีสมาชิกทั้งที่เป็นลิสต์และไม่เป็นลิสต์
nestlist4 = [1, 2, [3, 4, 5], 6, [7, 8, 9]]

In [11]:
print(nestlist1[0])

[1, 2, 3]


In [12]:
print(nestlist1[1][2])

6


In [13]:
print(nestlist2[2][1])

kiwi


In [14]:
print(nestlist3[1][0])

apple


In [15]:
print(nestlist4[2][1])

4


### ฟังก์ชันที่เกี่ยวกับลิสต์
1. `x.count(a)` ใช้นับจำนวนสมาชิกที่มีค่า `a` ในลิสต์ x
2. `x.sort()` ใช้จัดเรียงข้อมูลในลิสต์`x` จากน้อยไปหามาก
3. `x.reverse()` ใช้กลับลำดับของข้อมูลในลิสต์`x` จากเดิมซ้ายไปขวาให้เป็นขวาไปซ้าย
4. `x.clear()` ใช้ลบสมาชิกทั้งหมดในลิสต์ `x`

**ตัวอย่าง 1.7.3** พิจารณาลิสต์ต่อไปนี้

In [17]:
liblists=['math','statistics','NumPy','Pandas','Matplotlib','Seaborn','Scikit-Learn']
CCScore =[29.32,29,28,27,27.5,29,29,25,24,27,20]

In [18]:
liblists.count('Numpy')

0

In [22]:
CCScore.sort()
CCScore.reverse()
CCScore

[29.32, 29, 29, 29, 28, 27.5, 27, 27, 25, 24, 20]

In [ ]:
liblists.count('math')

1

In [ ]:
liblists.count('statistics')

1

In [ ]:
print(CCScore.count(29))

3


In [ ]:
CCScore.sort()
print(CCScore)

[20, 24, 25, 27, 27, 27.5, 28, 29, 29, 29, 29.32]


In [ ]:
CCScore.reverse()
print(CCScore)

[29.32, 29, 29, 29, 28, 27.5, 27, 27, 25, 24, 20]


In [ ]:
liblists.clear()
print(liblists)

[]


## 1.7.2 อาร์เรย์และเมทริกซ์

โครงสร้างข้อมูลประเภทอาร์เรย์และเมทริกซ์จะถูกจัดเก็บและเรียกใช้ภายใต้ไลบรารี numpy ภายในไลบรารีนี้มีฟังก์ชันมากกว่า 500 ฟังก์ชัน
กรณีต้องการเก็บค่าข้อมูลแบบอาร์เรย์หรือเมทริกซ์สามารถใช้คำสั่ง `numpy.array`
หรือ `np.array` หากตั้งเรียกชื่อไลบรารี `numpy` เป็น `np`

ถ้ากำหนดให้ $A=[a_{ij}]_{m\times n}$ เป็นเมทริกซ์ แล้ว คำสั่งในการสร้างเมทริกซ์ดังกล่าวคือ
```
A=numpy.array([[a11,a12,a13,...,a1n],[a21,a22,a23,...,a2n],...,[am1,am2,am3,...,amn]])
```

**หมายเหตุ:** ตัวแปร `A` ที่ประกาศแบบข้างต้นจะเป็นตัวแปรแบบเอเรย์ `n` มิติ (ndarrays)

**ตัวอย่าง 1.7.4**
จงสร้างเมทริกซ์ที่กำหนดให้ต่อไปนี้

(1) เมทริกซ์ $x$ ที่ไม่มีทั้งสมาชิกและขนาด

In [24]:
import numpy as np
x=np.array([])
print(x)

[]


In [23]:
import numpy as np
x = np.array([6,9,4,2,0])
x

array([6, 9, 4, 2, 0])

(2) เมทริกซ์แถว $y=
\begin{bmatrix}
  -1 & 0 & -3 & 2
\end{bmatrix}$

In [26]:
y=np.array([-1,0,-3,2])
print(y)

[-1  0 -3  2]


(3) เมทริกซ์หลัก $z=
\begin{bmatrix}
  -1 \\ 0\\ -3\\ 2
\end{bmatrix}$

In [30]:
z = np.array([[-1],[0],[-3],[2]])
z

array([[-1],
       [ 0],
       [-3],
       [ 2]])

In [27]:
z=np.array([[-1],[0],[-3],[2]])
print(z)

[[-1]
 [ 0]
 [-3]
 [ 2]]


(4) เมทริกซ์ $A=
\begin{bmatrix}
  -1 & -2 & 3\\
   0 & 0.1& 8\\
  -3 & 4& 2\\
   2 & -0.05& 9
\end{bmatrix}$

In [31]:
A=np.array([[-1,-2,3],[0,0.1,8],[-3,4,2],[2,-0.05,9]])
print(A)

[[-1.   -2.    3.  ]
 [ 0.    0.1   8.  ]
 [-3.    4.    2.  ]
 [ 2.   -0.05  9.  ]]


### ฟังก์ชันของเมทริกซ์ที่มีสมบัติเฉพาะ
นอกจากนี้ ในภาษาไพทอนได้มีการสร้างฟังก์ชันสำหรับเมทริกซ์ที่มีลักษณะเฉพาะต่างๆ ที่ถูกนำมาใช้ในการคำนวณบ่อย ดังนี้
- `numpy.zeros([m,n])` เป็นคำสั่งสำหรับสร้างเมทริกซ์ศูนย์ขนาด $m\times n$
- `numpy.eye(m,n)` เป็นคำสั่งสำหรับสร้างเมทริกซ์เอกลักษณ์ขนาด $m\times n$
- `numpy.ones([m,n])` เป็นคำสั่งสร้างเมทริกซ์ขนาด $m\times n$ ที่มีสมาชิกทั้งหมดเท่ากับ 1
- `numpy.diag(v)` เป็นคำสั่งหรับสร้างเมริกซ์แยงมุมที่สมาชิกในแนวทแยงมุมคือสมาชิกในลิสต์ $v$

**ตัวอย่าง 1.7.5**
จงเขียนคำสั่งภาษาไพทอนเพื่อสร้างเมทริกซ์ดังต่อไปนี้
1. เมทริกซ์ $B$ ที่เป็นเมทริกซ์ศูนย์ที่มีขนาด $3\times 4$
2. เมทริกซ์เอกลักษณ์ $C$ ที่มีขนาด $4\times 4$
3. เมทริกซ์ $D$ ที่มีขนาด $3\times 4$ ที่มีสมาชิกทั้งหมดเป็น $1$
4. เมทริกซ์ทแยงมุม
$
E=\begin{bmatrix}
-1 & 0 & 0\\
0& 0.5& 0\\
0& 0& 4
\end{bmatrix}
$

In [32]:
B = np.zeros([3,4])
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
C = np.eye(4,4)
C

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
D = np.ones([4,4])
D

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
E = np.diag([1,2,3,4,5])
E

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [40]:
import numpy as np
B=np.zeros([3,4])
print(B)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [41]:
C=np.eye(4,4)
print(C)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [42]:
D=np.ones([4,4])
print(D)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [43]:
E=np.diag([-1,0.5,4])
print(E)

[[-1.   0.   0. ]
 [ 0.   0.5  0. ]
 [ 0.   0.   4. ]]


### การดำเนินการเกี่ยวกับอาร์เรย์และเมทริกซ์
ตัวดำเนินการทางคณิตศาสตร์ที่สำคัญเกี่ยวกับอาร์เรย์และเมทริกซ์แสดงดังตารางต่อไปนี้

| ตัวดำเนินการ            | สัญลักษณ์ |
|-----------------------|--------|
| การบวก                | +      |
| การลบ                 | -      |
| การคูณ                 | @      |
| การคูณสมาชิกต่อสมาชิก     | *      |
| การยกกำลังของแต่ละสมาชิก | **     |
| การหารสมาชิกต่อสมาชิก    | /      |

**ตัวอย่าง 1.7.6**
กำหนดให้

$A=\begin{bmatrix}
2&2&2&2\\
2&2&2&2\\
2&2&2&2\\
2&2&2&2
\end{bmatrix}$ และ
$B=\begin{bmatrix}
5&4&3&2\\
2&3&4&5\\
1&-1&1&-1\\
4&4&4&4
\end{bmatrix}$


In [44]:
import numpy as np
A=2*np.ones([4,4])
B=np.array([[5,4,3,2],[2,3,4,5],[1,-1,1,-1],[4,4,4,4]])

In [45]:
A

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [46]:
B

array([[ 5,  4,  3,  2],
       [ 2,  3,  4,  5],
       [ 1, -1,  1, -1],
       [ 4,  4,  4,  4]])

จงบอกคำสั่งเพื่อหาค่าของ
1. $A+B$
2. $A-B$
3. $AB$
4. $A^4$
5. $C=[a_{ij}b_{ij}]_{4\times 4}$
6. $D=\left[\frac{a_{ij}}{b_{ij}}\right]_{4\times 4}$ เมื่อ $a_{ij}\in A$ และ $b_{ij}\neq 0\in B$

In [47]:
A+B

array([[7., 6., 5., 4.],
       [4., 5., 6., 7.],
       [3., 1., 3., 1.],
       [6., 6., 6., 6.]])

In [48]:
A-B

array([[-3., -2., -1.,  0.],
       [ 0., -1., -2., -3.],
       [ 1.,  3.,  1.,  3.],
       [-2., -2., -2., -2.]])

In [49]:
A@B

array([[24., 20., 24., 20.],
       [24., 20., 24., 20.],
       [24., 20., 24., 20.],
       [24., 20., 24., 20.]])

In [50]:
A@A@A@A

array([[1024., 1024., 1024., 1024.],
       [1024., 1024., 1024., 1024.],
       [1024., 1024., 1024., 1024.],
       [1024., 1024., 1024., 1024.]])

In [51]:
A*B

array([[10.,  8.,  6.,  4.],
       [ 4.,  6.,  8., 10.],
       [ 2., -2.,  2., -2.],
       [ 8.,  8.,  8.,  8.]])

In [52]:
A/B

array([[ 0.4       ,  0.5       ,  0.66666667,  1.        ],
       [ 1.        ,  0.66666667,  0.5       ,  0.4       ],
       [ 2.        , -2.        ,  2.        , -2.        ],
       [ 0.5       ,  0.5       ,  0.5       ,  0.5       ]])

In [54]:
print(A+B)

[[7. 6. 5. 4.]
 [4. 5. 6. 7.]
 [3. 1. 3. 1.]
 [6. 6. 6. 6.]]


In [55]:
print(A-B)

[[-3. -2. -1.  0.]
 [ 0. -1. -2. -3.]
 [ 1.  3.  1.  3.]
 [-2. -2. -2. -2.]]


In [56]:
print(A@B)

[[24. 20. 24. 20.]
 [24. 20. 24. 20.]
 [24. 20. 24. 20.]
 [24. 20. 24. 20.]]


In [57]:
print(A@A@A@A)

[[1024. 1024. 1024. 1024.]
 [1024. 1024. 1024. 1024.]
 [1024. 1024. 1024. 1024.]
 [1024. 1024. 1024. 1024.]]


In [58]:
#ทดลองเปรียบเทียบกับการดำเนินการ **
print(A**4)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [59]:
C=A*B
print(C)

[[10.  8.  6.  4.]
 [ 4.  6.  8. 10.]
 [ 2. -2.  2. -2.]
 [ 8.  8.  8.  8.]]


In [60]:
D=A/B
print(D)

[[ 0.4         0.5         0.66666667  1.        ]
 [ 1.          0.66666667  0.5         0.4       ]
 [ 2.         -2.          2.         -2.        ]
 [ 0.5         0.5         0.5         0.5       ]]


## 1.7.3 การอ้างอิงสมาชิกในอาร์เรย์หรือเมทริกซ์และการนำไปใช้

กำหนดให้ `v`เป็นอาร์เรย์ 1 มิติใดๆ จะได้ว่า
* `v[0]`เป็นการอ้างอิงสมาชิกของ v ในลำดับที่ $1$
* `v[-1]`เป็นการอ้างอิงสมาชิกของ v ในลำดับสุดท้าย
* `v[k]`เป็นการอ้างอิงสมาชิกของ v ที่ดัชนีที่ $k$ (ลำดับที่ k+1)
* `v[r1:r2:a]` อ้างอิงสมาชิกของ v ในลำดับที่กำหนดโดยดัชนี 𝑟1 ถึง 𝑟2-1 โดยเว้นระยะห่าง 𝑎
* `v[k]=a` แทนค่าข้อมูลที่ $k$ ด้วย $a$

กำหนดให้ `A`เป็นอาร์เรย์ 2 มิติใดๆ จะได้ว่า

* `A[r,c]` อ้างอิงสมาชิกแถวที่ $r-1$ หลักที่ $c-1$ ของ A
* `A[r,:]` หรือ `A[r]` อ้างอิงสมาชิกแถวที่ $r-1$ ทั้งแถวของ A
* `A[:,c]` อ้างอิงสมาชิกในหลักที่ $c-1$ ทั้งหมด
* `A[r1:r2,:]` หรือ `A[r1:r2]` อ้างอิงสมาชิกแถวที่ $r1$ ถึง $r2-1$ ทั้งหมดของ `A`
* `A[:,c1:c2]` อ้างอิงสมาชิกหลักที่ $c 1$ ถึง $c 2-1$ ของ A
* `A[r1:r2,c1:c2]` อ้างอิงสมาชิกแถวที่ $r1+1$ ถึง $r2$ และหลักที่ $c1+1$ ถึง $c2$ ของ A
* `A[r1:r2:a,c1:c2:b]` อ้างอิงสมาชิกแถวที่ $r1+1$ ถึง $r2$ และหลักที่ $c1+1$ ถึง $c2$ ของ A โดยเว้นระยะห่างตามแถวและหลักเป็น `a` และ `b` ตามลำดับ

**ตัวอย่าง 1.7.7**

กำหนดให้ $$v=[0\; 2\; 4\; 6\; 8\; 10\; 12\; 14\; 16\; 18\; 20]$$ และ
$$A=
\begin{bmatrix}
-1& 0& 4& 3& 8& 9& -2& 8\\
 2& -2& 3& 4& -5& 3& 2& 1\\
 3& 4& 5& 6& -8& 9& 7& 1\\
 1& -1& 2& 3& 2& 1& 1& 0\\
 0& 1& 0& 2& -3& 4& 8& 0.1
\end{bmatrix}$$
ดังคำสั่งต่อไปนี้

In [62]:
import numpy as np
v=np.array([0,2,4,6,8,10,12,14,16,18,20])
A=np.array([[-1,0,4,3,8,9,-2,8],[2,-2,3,4,-5,3,2,1],[3,4,5,6,-8,9,7,1],[1,-1,2,3,2,1,1,0],[0,1,0,2,-3,4,8,0.1]])

In [64]:
v

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [65]:
A

array([[-1. ,  0. ,  4. ,  3. ,  8. ,  9. , -2. ,  8. ],
       [ 2. , -2. ,  3. ,  4. , -5. ,  3. ,  2. ,  1. ],
       [ 3. ,  4. ,  5. ,  6. , -8. ,  9. ,  7. ,  1. ],
       [ 1. , -1. ,  2. ,  3. ,  2. ,  1. ,  1. ,  0. ],
       [ 0. ,  1. ,  0. ,  2. , -3. ,  4. ,  8. ,  0.1]])

จงบอกคำสั่งที่ทำให้ได้ผลลัพธ์ต่อไปนี้

(1) อ้างอิงสมาชิกตัวแรกของ $v$

In [63]:
print(v[0])

0


(2) อ้างอิงสมาชิกตัวสุดท้ายของ $v$

In [66]:
print(v[-1])
# หรือ
print(v[10])

20
20


(3) สร้างเวกเตอร์ $x=[0~2~4~6~8~10~12~14]$ จาก $v$

In [69]:
x = v[:8]
x

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [ ]:
x=v[0:8]
print(x)

[ 0  2  4  6  8 10 12 14]


(4) สร้างเวกเตอร์ $y=[0~4~8~12~16~20]$ จาก $v$

In [74]:
y = v[::2]
y

array([ 0,  4,  8, 12, 16, 20])

In [ ]:
y=v[0:11:2]
print(y)

[ 0  4  8 12 16 20]


(5) สร้างเวกเตอร์ $z=[0~6~12~18]$ จาก $v$

In [77]:
z= v[::3]
z

array([ 0,  6, 12, 18])

In [ ]:
z=v[0:11:3]
print(z)

[ 0  6 12 18]


(6) อ้างอิง $a_{11}\in A$

In [80]:
A[0,0]

-1.0

In [ ]:
print(A[0,0])

-1.0


(7) อ้างอิงสมาชิกที่อยู่ใแถวสุดท้ายและหลักสุดท้ายของ $A$

In [ ]:
print(A[-1,-1])

0.1


(8) สมาชิกในแถวที่ 2 ของ $A$ ทั้งหมด

In [84]:
A[1,:]

array([ 2., -2.,  3.,  4., -5.,  3.,  2.,  1.])

In [ ]:
print(A[1,:])

[ 2. -2.  3.  4. -5.  3.  2.  1.]


(9) สมาชิกในหลักที่ 3 ของ $A$

In [85]:
A[:,2]

array([4., 3., 5., 2., 0.])

In [83]:
A[:,2]

array([4., 3., 5., 2., 0.])

In [ ]:
print(A[:,2])

[4. 3. 5. 2. 0.]


(11) เมทริกซ์ $B=
\begin{bmatrix}
  0&  4&  3\\
  -2&  3&  4\\
\end{bmatrix}$ จาก $A$

In [88]:
B = A[:2,1:4]
B

array([[ 0.,  4.,  3.],
       [-2.,  3.,  4.]])

In [ ]:
B=A[0:2,1:4]
print(B)

[[ 0.  4.  3.]
 [-2.  3.  4.]]


(12) เมทริกซ์ $C=
\begin{bmatrix}
0& 3& 9\\
4& 6& 9\\
1& 2& 4
\end{bmatrix}$ จาก $A$

In [95]:
C = A[:5:2,1:6:2,]
C

array([[0., 3., 9.],
       [4., 6., 9.],
       [1., 2., 4.]])

In [ ]:
C=A[0:5:2,1:6:2]
print(C)

[[0. 3. 9.]
 [4. 6. 9.]
 [1. 2. 4.]]


(14) เมทริกซ์ $D=
\begin{bmatrix}
 0&  9\\
-1&  1
\end{bmatrix}$ จาก $A$

In [96]:
D = A[::3,1::4]
D

array([[ 0.,  9.],
       [-1.,  1.]])

In [97]:
D=A[0:4:3,1:6:4]
print(D)

[[ 0.  9.]
 [-1.  1.]]


# 1.7.4 คำสั่งที่เกี่ยวข้องอื่นๆ

- `numpy.transpose(A)` เป็นฟังก์ชันสำหรับหาค่าทรานสโพสของอาร์เรย์ $A$
- `numpy.size(A)` เป็นฟังก์ชันสำหรับหาค่าจำนวนสมาชิกทั้งหมดของอาร์เรย์ $A$
- `numpy.shape(A)` เป็นฟังก์ชันสำหรับหาค่าขนาดของอาร์เรย์ $A$
- `numpy.linspace(a,b,n)` เป็นฟังก์ชันสำหรับสร้างเมทริกซ์แถวขนาด $1 \times n$ ที่มีสมาชิกตัวแรกเท่ากับ $a$ สมาชิกตัวถัดไปเพิ่มขึ้น $\frac{b-a}{n-1}$ และสมาชิกตัวสุดท้ายเท่ากับ $b$
- `numpy.abs(A)` เป็นฟังก์ชันสำหรับหาค่าสัมบูรณ์ของสมาชิกทั้งหมดของอาร์เรย์ $A$

- `numpy.floor(A)` เป็นฟังก์ชันสำหรับหาค่าจำนวนเต็มที่มากที่สุดที่น้อยกว่าของแต่ละสมาชิกของอาร์เรย์ $A$

- `numpy.ceil(A)` เป็นฟังก์ชันสำหรับหาค่าจำนวนเต็มที่น้อยที่สุดที่มากกว่าของแต่ละสมาชิกของอาร์เรย์ $A$

- `numpy.round(A)` เป็นฟังก์ชันสำหรับปัดเศษให้เป็นจำนวนเต็มที่ใกล้เคียงที่สุดของแต่ละสมาชิกของอาร์เรย์ $A$

- `numpy.random`เป็นฟังก์ชันสำหรับสร้างเมททริกซ์สุ่มแบบต่างๆ ซึ่งมีคำสั่งย่อยต่างๆ เช่น

  - `numpy.random.rand(m,n)` เป็นฟังก์ชันเกี่ยวกับสร้างเมทริกซ์ขนาด $m\times n$ ที่สมาชิกเกิดจากการแจกแจงแบบเอกรูปในช่วง $[0,1]$

  - `numpy.random.randn(m,n)` เป็นฟังก์ชันเกี่ยวกับสร้างเมทริกซ์ขนาด $m\times n$ ที่สมาชิกเกิดจากการแจกแจงแบบปกติมาตรฐาน

**ตัวอย่าง 1.7.8**

1. จงสร้างเวกเตอร์ $A=[0~0.1~0.2~0.3~0.4~0.5~0.6~0.7~0.8~ 0.9~1.]$ ด้วยคำสั่ง `numpy.linspace`
2. หาจำนวนสมาชิกทั้งหมดของ $A$ ในข้อ 1
3. หาจำนวนแถวและหลักของ $A$
4. สร้างเมทริกซ์ $C$ ที่มีขนาด $4\times 7$ โดยที่สมาชิกทุกตัวของ $C$ เกิดจากการสุ่มแบบเอกรูปในช่วง [-4,3]
5. สร้างเมทริกซ์ $D$ ที่มีขนาด $5\times 5$ โดยที่สมาชิกทุกตัวของ $D$ เกิดจากการสุ่มแบบปรกติมาตรฐาน



In [105]:
A = np.linspace(0,1,11)
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [106]:
np.size(A)

11

In [107]:
np.shape(A)

(11,)

In [113]:
C = np.random.rand(4,7)*3 - 4
C

array([[-2.89600128, -2.79167065, -1.32056567, -3.4813577 , -3.90764577,
        -2.30554991, -3.12711915],
       [-3.00316141, -1.90493155, -1.54219288, -3.86912278, -2.49327122,
        -1.23572986, -3.30744965],
       [-2.5714679 , -2.22129459, -3.5937549 , -3.39359189, -2.54918041,
        -1.79116931, -2.53713393],
       [-1.53375815, -2.66097396, -3.73723506, -3.91618598, -3.61869738,
        -1.98764947, -1.28193838]])

In [111]:
D = np.random.randn(5,5)
D

array([[-0.63920373, -0.22987306, -0.24060168, -0.61388832,  0.03622021],
       [-2.17087048,  0.76378427, -0.4809119 ,  0.99997914, -0.94901694],
       [-0.01495635, -0.00350117,  0.13308444,  0.28643079,  0.37553302],
       [-0.27283163, -0.01975631,  2.29386908, -2.12370845,  1.22157051],
       [-0.42177829, -1.28286586, -0.74692965,  0.92229783, -0.43257298]])

In [114]:
import numpy as np

In [115]:
A=np.linspace(0,1,11)
print(A)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [116]:
sizeA=np.size(A)
print(sizeA)

11


In [117]:
shA=np.shape(A)
print(shA)

(11,)


In [118]:
C=-4+7*np.random.rand(4,7)
print(C)

[[ 0.12901067 -2.28785351  2.92201316 -1.83909575  1.20701163  0.75941626
  -0.40072005]
 [-0.49978324 -0.25879391 -2.29363583  0.94587652 -1.95078569 -2.01659462
  -3.37662582]
 [-3.73531624  2.35097435 -2.30443579  0.58398208 -2.00914224  1.36572642
  -3.89288655]
 [ 0.03253654 -2.07526032 -2.40485137  1.21077534 -2.4797063   0.69845365
  -0.77015266]]


In [119]:
D=np.random.randn(5,5)
print(D)

[[ 0.81859571  1.45169153  1.21418878  0.23007963  0.61664604]
 [-1.26176891  0.66574938 -2.4552638  -0.11610223  0.24557708]
 [-1.13569377 -0.13480211 -0.27580247 -0.08318376 -0.02682847]
 [-0.23262535 -0.71384164 -0.46318998  0.12591206  1.58721109]
 [ 1.19450659  0.09558105  0.80358038 -0.82313008  0.19532111]]


# เอกสารอ้างอิง
1. Python Language. https://www.python.org
2. math — Mathematical functions: https://docs.python.org/3/library/math.html
3. Numpy Library: https://numpy.org


<img src = 'https://drive.google.com/uc?id=18qUXmnQK3FIPfMCm8m0aKf1Saam6ezdJ'>

<img src = 'https://drive.google.com/uc?id=192V5NZG8GXDFzYQIxTRJCSmiBUkc2xys'>