<a href="https://colab.research.google.com/github/Angy-face/Esan-Coding-SS2/blob/main/Course2Topic1Part4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src = 'https://drive.google.com/uc?id=18zsxFId1FaUI1RvfkAex6ZoNpToP8GoT'>

---

# ผู้บรรยาย: ผู้ช่วยศาสตราจารย์ ดร. วีระชัย สาระคร
## สาขาวิชาคณิตศาสตร์ คณะวิทยาศาสตร์ มหาวิทยาลัยขอนแก่น

---

# Topic 1: Basic Python Programming for Data Scientists

# 1.8 การสร้างฟังก์ชันแบบกำหนดเอง (User-defined function)
การเขียนโปรแกรมที่ผ่านมาจะเป็นการเขียนโปรแกรมแบบใช้ชุดคำสั่งที่บางครั้งมีการเรียกใช้งานฟังก์ชันที่มีอยู่ในไลบรารีหรือมอดูลที่มีอยู่แล้วมาใช้ในการแก้ปัญหา
ในกรณีที่ผู้ใช้งานต้องการสร้างฟังก์ชันเพื่อต้องการแก้ปัญหาเฉพาะที่ไม่ได้มีอยู่ในไลบรารีหรือมอดูล ก็สามารถสร้างฟังก์ชันทำได้โดยกำหนดการเขียนฟังก์ชันขึ้นมาเอง ซึ่งการเขียนโปรแกรมลักษณะนี้เรียกว่า การเขียนฟังก์ชันแบบกำหนดเอง ลักษณะการเขียนฟังก์ชันอย่างง่ายในภาษาไพทอนเป็นดังนี้

```
def func_name(inputs):
    statements
    return output(s)
```
ซึ่งจะเห็นว่าส่วนประกอบของฟังก์ชันประกอบด้วยคำสำคัญ `def` ชื่อฟังก์ชัน `func_name`
ตัวแปรข้อมูลเข้า `inputs` (จะไม่มีหรือมีได้หลายตัวแปรได้) ตัวแปรออก `output` จะมีหรือไม่มีก็ได้ หากมีเกินหนึ่งตัวแปรให้คั่นด้วย `,`


**ตัวอย่าง 1.8.1**
จงเขียนฟังก์ชันด้วยภาษาไพทอนเพื่อคำนวณค่าปริมาตรของทรงกระบอก $$V=\pi r^2 h$$ เมื่อ $r$ เป็นรัศมีและ $h$ เป็นความสูง โดยตั้งชื่อฟังก์ชันเป็น `VolumeOfCylinder`

In [ ]:
def VolumeOfCylinder(r,h):
  import math
  V=math.pi*r**2*h
  return V

* ตัวอย่างการเรียกใช้งานแบบที่ 1

In [ ]:
r=10
h=20
V=VolumeOfCylinder(r,h)
print(V)

6283.185307179587


* ตัวอย่างการเรียกใช้งานแบบที่ 2

In [ ]:
x1=10
x2=20
x3=VolumeOfCylinder(x1,x2)
print(x3)

6283.185307179587


* ตัวอย่างการเรียกใช้งานแบบที่ 3

In [ ]:
v=VolumeOfCylinder(10,20)
print(v)

6283.185307179587


**ตัวอย่าง 1.8.2**
จงสร้างฟังก์ชันแบบกำหนดเองเพื่อคำนวณค่า $$F(x,y)=x^3+3x^2y-3xy^2-y^3$$

In [ ]:
def F(x ,y):
  res = x**3+3*x**2*y-3*x*y**2-y**3
  return res

ชุดคำสั่งในการสร้างฟังก์ชันเป็นดังนี้

In [ ]:
def Fxy(x,y):
  F=x**3+3*x**2*y-3*x*y**2-y**3
  return F

ตัวอย่างการเรียกใช้งาน

In [ ]:
x=2
y=1
z=Fxy(x,y)
c =F(x,y)
print(z,c,z == c)

13 13 True


## การสร้าง lambda ฟังก์ชัน

Lambda function หรือ Anonymous function เป็นฟังก์ชันนิพจน์ที่แสดงถึงค่าของฟังก์ชันซึ่งสามารถสร้างและเก็บค่าไว้ในตัวแปร หรือส่งเป็นพารามิเตอร์ของฟังก์ชันอื่นได้โดยไม่จำเป็นต้องมีชื่อในการประกาศ ดังนั้นรูปแบบการประกาศของฟังก์ชันประเภทนี้จึงสั้นและเรียบง่าย ที่สำคัญมันสามารถมีได้เพียงหนึ่งคำสั่ง (Expression)และ จะเป็นค่าส่งกลับของฟังก์ชันเสมอ

**ตัวอย่าง 1.8.3** การสร้าง lambda ฟังก์ชันสำหรับการหาปริมาตรของทรงกระบอกที่ใช้สูตรการคำนวณในตัวอย่าง 1.8.1 เป็นดังนี้

In [ ]:
import math
Volume =lambda r,h: math.pi*r**2*h
print(Volume(10,20))

6283.185307179587


# 1.9 การเขียนโปรแกรมแบบควบคุมทิศทาง


## 1.9.1 การเขียนโปรแกรมแบบกำหนดเงื่อนไขการทำงาน

สำหรับการเขียนโปรแกมภาษาไพทอนที่ผ่านมาจะเป็นการเขียนโปรแกรมเพื่อสั่งการให้แก้ปัญหาโดยไม่ได้มีการกำหนดเงื่อนไขการทำงาน แต่ในบางครั้งหากการแก้ปัญหาจำเป็นต้องมีการเลือกเงื่อนไขในการทำงาน

### คำสั่ง `if`
**รูปแบบคำสั่ง**

```
if condition :
  statements
```
เป็นคำสั่งที่กำหนดเงื่อนไขการทำงานอย่างง่าย เมื่อคอมพิวเตอร์ประมวลผลมาพบคำสั่งนี้ จะทำการตรวจสอบเงื่อนไข `condition` ว่าเงื่อนไขนี้เป็นจริงหรือไม่ ถ้าจริง จะประมวลผลคำสั่ง `statements` ทั้งหมด แต่ถ้า `condition` เป็นเท็จ คอมพิวเตอร์ก็จะข้ามคำสั่ง `statements` แล้วไปพิจารณาคำสั่งแรกที่อยู่ในบรรทัดถัดไปจาก `statements` การพิมพ์คำสั่ง`statements` ต่างๆภายใต้เงื่อนไขจะต้องย่อหน้าเข้าไปเสมอ
ทิศทางการทำงานของโปรแกรมแสดงดังรูป

<img src = 'https://drive.google.com/uc?id=1JZNWPjlfqFlbVIDhqrun9CcRRv7uvhyh' width=500>


**ตัวอย่าง 1.9.1**
ปกติอุปกรณ์อิเล็กทรอนิกพกพาเช่น มือถือ แท็บเล็ต สามารถทำงานได้ตามปกติในช่วงอุณหภูมิรอบข้างอยู่ระหว่าง $-20^\circ C$ ถึง $45^\circ C$ จงเขียนโปรแกรมให้อุปกรณ์ดังกล่าวขึ้นสถานะ

"Your device is being shut down because the ambient temperature exceeds a certain limit."

หากอุณหภูมิรอบข้างของอุปกรณ์ดังกล่าวที่วัดได้ในที่นี้สมมุติให้เป็น `temperature` ไม่ได้อยู่ในขอบเขตที่กำหนดไว้


ตัวอย่างการเขียนโปรแกรมเป็นดังนี้

In [1]:
temperature = 25
if temperature < -20 or temperature > 45:
  print ("Your device is being shut down because the ambient temperature exceeds a certain limit.")

### คำสั่ง `if-else`

**รูปแบบคำสั่ง**

```
if condition :
  statements1
else :
  statements2
```

เป็นคำสั่งที่กำหนดเงื่อนไขการทำงานเพียงอย่างใดอย่างหนึ่ง เมื่อคอมพิวเตอร์ประมวลผลมาพบคำสั่งนี้ จะทำการตรวจสอบเงื่อนไข `condition` ว่าเงื่อนไขนี้เป็นจริงหรือไม่ ถ้าจริง จะประมวลผลคำสั่ง `statements1` ทั้งหมด แต่ถ้า `condition` เป็นเท็จ คอมพิวเตอร์ก็จะข้ามไปประมวลผลคำสั่ง `statements2` จากนั้น เมื่อประมวลผล  `statements1` หรือ `statements2`เสร็จค่อยไปพิจารณาคำสั่งแรกที่อยู่ในบรรทัดถัดไปจาก `statements2`
คำสั่งที่อยู่ภายใต้เงื่อนไขต่างๆ จะต้องย่อหน้าเข้าไปเสมอ
ทิศทางการทำงานของโปรแกรมแสดงดังรูป

<img src = 'https://drive.google.com/uc?id=1J_q2Hoggh2Qa03r2vUotdNKuO74A_RiT' width=600>


**ตัวอย่าง 1.9.2**
จงเขียนโปรแแกรมสำหรับสถานการณ์สมมุติเกี่ยวกับการคัดเลือกผู้เข้าร่วมโครงการ Coding เพื่อเข้าสู่รอบ Hackathon เมื่อพิจารณาจากค่าคะแนน(%) ที่เก็บไว้ในตัวแปร `Coding_score` โดยเงื่อนไขการทำงานของโปรแกรมมีดังนี้

1. ถ้าคะแนน `Coding_score` $< 50$ ให้แสดงข้อความ 'ขอแสดงความเสียใจด้วยครับ คุณไม่ได้ผ่านเข้ารอบ Hackathon ไว้โอกาสหน้าพยายามใหม่'
2. ถ้าคะแนน `Coding_score` $\geq 50$ ให้แสดงข้อความ 'ขอแสดงความยินดีด้วยครับ  คุณคือผู้เข้าที่ได้ผ่านเข้ารอบ Hackathon ต่อไป'

In [ ]:
Coding_score = 51
if Coding_score < 50:
  print('ขอแสดงความเสียใจด้วยครับ คุณไม่ได้ผ่านเข้ารอบ Hackathon ไว้โอกาสหน้าพยายามใหม่ครับ')
else: # Coding_score >= 50
  print('ขอแสดงความยินดีด้วยครับ  คุณคือผู้ที่ได้ผ่านเข้ารอบ Hackathon ต่อไป')

ขอแสดงความยินดีด้วยครับ  คุณคือผู้ที่ได้ผ่านเข้ารอบ Hackathon ต่อไป


### คำสั่ง `if-elif-else`
**รูปแบบคำสั่ง**

```
if condition-1 :
  statements-1
elif condition-2 :
  statements-2
elif condition-3 :
  statements-3
  ...
else :
  statements-n
```
เป็นคำสั่งที่กำหนดเงื่อนไขการทำงาน $n$ เงื่อนไข เมื่อคอมพิวเตอร์ประมวลผลมาพบคำสั่งนี้ จะทำการตรวจสอบเงื่อนไข `condition-1` ว่าเงื่อนไขนี้เป็นจริงหรือไม่ ถ้าจริง จะประมวลผลคำสั่ง `statements-1` ทั้งหมด แต่ถ้า `condition-1` เป็นเท็จ คอมพิวเตอร์ก็จะข้ามทำการตรวจสอบเงื่อนไข `condition-2` ว่าเงื่อนไขนี้เป็นจริงหรือไม่ ถ้าจริง จะประมวลผลคำสั่ง `statements-2` ทั้งหมด แต่ถ้า `condition-2` เป็นเท็จ
ก็จะไปพิจารณาเงื่อนไขที่ 3 แบบนี้ไปเรื่อยๆ หากไม่สอดคล้องเงื่อนไขที่  1 ถึง เงื่อนไข $n-1$ เลยจะประมวลผล  `statements-n` จากนั้น ค่อยไปพิจารณาคำสั่งแรกที่อยู่ในบรรทัดถัดไปจาก `statements-n`

**หมายเหตุ** คำสั่งภายใต้เงือนไขต่างๆ จะต้องย่อหน้าเข้าไปเสมอ

ทิศทางการทำงานของโปรแกรมแสดงดังรูป

<img src = 'https://drive.google.com/uc?id=1JaPmCWH1oMd_XbZGM_ViKn0QoNgHDpdr' width=600>


**ตัวอย่าง 1.9.3**
จงเขียนโปรแกรมเพื่อคำนวณค่า
$f(x,y) =
\begin{cases}
    f(x,y) = x+y+2,x < 0, y < 0,\\
    f(x,y) = \pi x^3 +y^2,x < 0, y \geq 0,\\
    f(x,y) = \sin xy^2,x \geq 0, y < 0,\\
    f(x,y) = e^{-x^2-y^2+2}-1,x \geq 0, y \geq 0,\\
\end{cases}
$

In [6]:
def fun(x,y):
  import math
  if x < 0 and y <0:
    return x+y+2
  elif x < 0 and y >= 0:
    return math.pi*x**3 + y**2
  elif x >= 0 and y < 0:
    return math.sin(x*y**2)
  else :
    return math.exp(-x**2-y**2+2)-1

ตัวอย่างโปรแกรมของการคำนวณค่าฟังก์ชันที่กำหนดให้เป็นดังนี้

In [7]:
def fxy(x,y):
  import math
  if x<0 and y<0:
    z=x+y+2
  elif x<0 and y>=0:
    z=math.pi*x**3+y**2
  elif x>=0 and y<0:
    z=math.sin(x*y**2)
  else:#x>=0 and y>= 0
    z=math.exp(-x**2-y**2+2)-1
  return z

In [8]:

print(fxy(5,6),fun(5,6),fxy(5,6)==fun(5,6))

-1.0 -1.0 True


ตัวอย่างการเรียกใช้งานเป็นดังนี้

In [9]:
x=-1
y=5
z=fxy(x,y)
print('f({:f},{:f}) = {:f}'.format(x,y,z))

f(-1.000000,5.000000) = 21.858407


**ตัวอย่าง 1.9.4**
พิจารณาช่วงปีที่เกิด(ค.ศ.)และชื่อรุ่นของช่วงอายุของประชากรโลกดังตารางต่อไปนี้

| Generation Name          | Year interval |
|--------------------------|---------------|
|   Lost Generation        |   1883-1900   |
|   Greatest Generation    |   1901-1927   |
|       Silent Generation  |   1928-1945   |
|  Baby Boomer Generation  |   1946-1964   |
|       Generation X       |   1965-1980   |
|       Generation Y       |   1981-1996   |
|       Generation Z       |   1997-2012   |
|       Generation Alpha   |   2013-2025   |

จงเขียนโปรแกรมเพื่อให้ผู้ใช้งานป้อนค่าปีที่เกิด(ค.ศ.) `birth_year` และจัดเก็บให้เป็นจำนวนเต็ม จากนั้น ให้แสดงข้อความว่า รุ่นอายุของผู้ใช้งานคือรุ่นอะไร ตัวอย่างเช่น

You was born in 2000. So, you are in Generation Z.

In [10]:
birth_year=2023
if 1883<=birth_year<=1900:
  print('You was born in {}. So, you are in the Lost Generation.'.format(birth_year))
elif 1901<=birth_year<=1927:
  print('You was born in {}. So, you are in the Greatest Generation.'.format(birth_year))
elif 1928<=birth_year<=1945:
  print('You was born in {}. So, you are in the Silent Generation.'.format(birth_year))
elif  1946<=birth_year<=1964:
  print('You was born in {}. So, you are in the Baby Boomer Generation.'.format(birth_year))
elif  1965<=birth_year<=1980:
   print('You was born in {}. So, you are in the Generation X.'.format(birth_year))
elif  1981<=birth_year<=1996:
  print('You was born in {}. So, you are in the Generation Y.'.format(birth_year))
elif  1997<=birth_year<=2012:
  print('You was born in {}. So, you are in the Generation Z.'.format(birth_year))
elif  2013<=birth_year<=2025:
  print('You was born in {}. So, you are in the Generation Alpha.'.format(birth_year))
else:
  print('You was born in {}. So, you are undefined generation!!!.'.format(birth_year))

You was born in 2023. So, you are in the Generation Alpha.


## 1.9.2 การเขียนโปรแกรมแบบทำซ้ำ

### คำสั่ง `while`
**รูปแบบของคำสั่ง**
```
while condition :
  statements
```
เป็นคำสั่งที่ทำให้เกิดการทำงานแบบทำซ้ำ เมื่อคอมพิวเตอร์ประมวลผลคำสั่งนี้จะตรวจสอบเงื่อนไข `condition` ก่อนว่าเป็นจริงหรือไม่ ถ้าเป็นจริงจะประมวลผลคำสั่ง `statements` ทั้งหมด จากนั้นจะย้อนกลับไปตรวจสอบเงื่อนไข `condition` อีกครั้ง ถ้ายังคงเป็นจริงก็จะประมวลผลคำสั่งอีกครั้ง ทำแบบนี้ไปเรื่อยๆ จนกว่า เงื่อนไข `condition` จะเป็นเท็จ จึงหยุดการทำซ้ำนี้ แล้วค่อยไปประมวลผลคำสั่งที่อยู่ถัดจากนี้ คำสั่งที่อยู่ภายใต้การทำซ้ำแบบ `while` จะต้องเขียนย่อหน้าเข้าไปเสมอ
ทิศทางการทำงานภายใต้คำสั่ง `while` เป็นดังรูป

<img src = 'https://drive.google.com/uc?id=1Jbk9EkBQGmAWgGIUTxXqWV5ufZqctnPD' width=400>


**ตัวอย่าง 1.9.5**
จงเขียนโปรแกรมด้วยภาษาไพทอนโดยใช้ While loop เพื่อหาผลบวกดังต่อไปนี้
$$1\cdot2 + 2\cdot 3 + 3\cdot 4 + ... + n\cdot(n+1)$$


In [25]:
n = 20
i=1
sum = 0
while i <= n:
  sum += i *(i +1)
  i+=1
print(sum)

3080


ตัวอย่างโปรแกรมเป็นดังนี้

In [16]:
n=20
sum=0
i=1
while i<=n:
  sum=sum+i*(i+1)
  if i<n:
    print('{}*{} + '.format(i,i+1),end='')
  else:
    print('{}*{}'.format(i,i+1),end='')
  i=i+1
print('= {}'.format(sum))

1*2 + 2*3 + 3*4 + 4*5 + 5*6 + 6*7 + 7*8 + 8*9 + 9*10 + 10*11 + 11*12 + 12*13 + 13*14 + 14*15 + 15*16 + 16*17 + 17*18 + 18*19 + 19*20 + 20*21= 3080


**ตัวอย่าง 1.9.6**
จงเขียนโปรแกรมด้วยคำสั่ง `while` เพื่อคำนวณค่าลำดับของฟิโบนักชี $F_{n} = F_{n-1} + F_{n-2}$ เมื่อกำหนดให้ผู้ใช้งานป้อนค่า $F_{0}$ และ $F_{1}$ และ $n$ จากแป้นพิมพ์


In [49]:
import numpy as np

N = 20
F = np.zeros([N+1,1])
F[0] = 1
F[1] = 2
i = 2
while i<=N:
  F[i] = F[i-1]+F[i-2]
  print(F[i])
  i +=1

print(F[N+1])

[3.]
[5.]
[8.]
[13.]
[21.]
[34.]
[55.]
[89.]
[144.]
[233.]
[377.]
[610.]
[987.]
[1597.]
[2584.]
[4181.]
[6765.]
[10946.]
[17711.]


IndexError: index 21 is out of bounds for axis 0 with size 21

ตัวอย่างโปรแกรมเป็นดังนี้

In [50]:
import numpy as np
F0=int(input('Input F[0] = '))
F1=int(input('Input F[1] = '))
n=int(input('Input n = '))
F=np.zeros([n+1,1])
F[0] = F0
F[1] = F1
i=2
while i<=n:
  F[i]=F[i-1]+F[i-2]
  print('F[{}] = {}'.format(i,int(F[i])))
  i=i+1

KeyboardInterrupt: Interrupted by user

### คำสั่ง `for`
**รูปแบบที่ 1**

```
for iterator in sequence:
  statements
```
เมื่อ `iterator` ตัวแปรที่ใช้ในการทำซ้ำ `sequence` ตัวแปรที่มีลำดับข้อมูล

**รูปแบบที่ 2: กรณีใช้ range**
```
for index in range(bound) :
  statements
```
เมื่อ `index` เป็น ดัชนีของรอบการทำซ้ำ `bound` เป็นขอบเขตของการทำซ้ำ
รูปแบบการกำหนด `range` เพิ่มเติมเป็นดังนี้
```
range(start,stop,step)
```
เมื่อ `start` เป็นดัชนีเริ่มต้น `stop` เป็นดัชนีสุดท้าย `step` เป็นระยะห่าง

คำสั่ง `for` เป็นคำสั่งที่ทำให้เกิดการทำงานแบบทำซ้ำอีกหนึ่งรูปแบบ เมื่อคอมพิวเตอร์ประมวลผลคำสั่งนี้ จะทราบจำนวนรอบที่แน่นอนโดยจะมีดัชนีของรอบเป็นตัวกำหนดรอบการทำซ้ำ แต่ละรอบการทำซ้ำ คอมพิวเตอร์จะประมวลผลคำสั่ง `statements` ทุกรอบ เมื่อเสร็จแล้วสั่งไปประมวลผลคำสั่งที่อยู่หลังคำสั่งนี้ คำสั่งทั้งหมดที่อยู่ภายใต้ `for` จะต้องย่อหน้าเข้าไปเสมอ
ทิศทางการทำงานภายใต้คำสั่ง `for` แสดงดังรูป

<img src = 'https://drive.google.com/uc?id=1Jbym-OVowPCq2Fw0TVqtTkC_g2B0FLE6' width=500>


**ตัวอย่าง 1.9.7**
จงเขียนโปรแกรมด้วยภาษาไพทอนโดยใช้ for loop เพื่อแสดงรายชื่อบุคคลที่รวยที่สุดในโลก 5 อันดับแรกดังนี้

Elon Musk, Bernard Arnault, Jeff Bezos, Bill Gates, Larry Ellison


In [51]:
name_list=['Elon Musk','Bernard Arnault','Jeff Bezos','Bill Gates','Larry Ellison']

**กรณีใช้คำสั่ง `for` แบบที่ 1**

In [52]:
for name in name_list:
  print(name)

Elon Musk
Bernard Arnault
Jeff Bezos
Bill Gates
Larry Ellison


**กรณีใช้คำสั่ง `for` แบบที่ 2**

In [53]:
Ndat=len(name_list)
for name in range(0,Ndat):
  print('{}. {}'.format(name+1,name_list[name]))

1. Elon Musk
2. Bernard Arnault
3. Jeff Bezos
4. Bill Gates
5. Larry Ellison


**ตัวอย่าง 1.9.8** นักเตะที่มีค่าตัวการย้ายทีมสูงที่สุดในโลกตลอดกาล 10 อันดับแรกเป็นดังนี้
1. เนย์มาร์ : 222 ล้านยูโร
2. คิลิยัน เอ็มบัปเป้ : 180 ล้านยูโร
3. ฟิลิปเป้ คูตินโญ่ : 145 ล้านยูโร
4. เจา เฟลิกซ์ : 126 ล้านยูโร
5. เอ็นโซ่ เฟอร์นานเดซ : 121 ล้านยูโร
6. อองตวน กรีซมันน์ : 120 ล้านยูโร
7. แจ็ค กรีลิช : 117 ล้านยูโร
8. ดีแคลน ไรซ์ : 117 ล้านยูโร
9. มอยเซส ไกเซโด : 117 ล้านยูโร
10. โรเมลู ลูกากู : 115 ล้านยูโร

จงเขียนโปรแกรมหาค่าเฉลี่ยของค่าตัวของนักเตะในหน่วยล้านยูโรโดยใช้คำสั่ง `for` (แสดงทศนิยม 4 ตำแหน่ง)

In [54]:
import numpy as np
player_transfer=np.array([222,180,145,126,121,120,117,117,117,115])
sumval=0
for value in player_transfer:
  sumval=sumval+value
meanval=sumval/len(player_transfer)
print('The average of player transfer is {:.4f} million euros'.format(meanval))

The average of player transfer is 138.0000 million euros


**ตัวอย่าง 1.9.9**
จงเขียนโปรแกรมด้วยภาษาไพทอนเพื่อคำนวณค่าลำดับของฟิโบนักชีที่กำหนดไว้ในตัวอย่าง 1.9.6 ด้วยคำสั่ง `for`


ตัวอย่างโปรแกรมเป็นดังนี้

In [56]:
import numpy as np
F0=int(input('Input F[0] = '))
F1=int(input('Input F[1] = '))
n=int(input('Input n = '))
F=np.zeros([n+1,1])
F[0] = F0
F[1] = F1
for i in range(2,n+1):
  F[i]=F[i-1]+F[i-2]
  print('F[{}] = {}'.format(i,int(F[i])))

Input F[0] = 1
Input F[1] = 2
Input n = 20
F[2] = 3
F[3] = 5
F[4] = 8
F[5] = 13
F[6] = 21
F[7] = 34
F[8] = 55
F[9] = 89
F[10] = 144
F[11] = 233
F[12] = 377
F[13] = 610
F[14] = 987
F[15] = 1597
F[16] = 2584
F[17] = 4181
F[18] = 6765
F[19] = 10946
F[20] = 17711


<ipython-input-56-5d9a048089c5>:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print('F[{}] = {}'.format(i,int(F[i])))


## 1.9.3 การประยุกต์การเขียนโปรแกรมแบบกำหนดเงื่อนไขและแบบทำซ้ำร่วมกัน
ตัวอย่างต่อไปนี้แสดงการประยุกต์ใช้การเขียนโปรแกรมแบบควบคุมทิศทางแบบต่างๆ ร่วมกันเพื่อแก้ปัญหาในสถานการณ์ปัญหาต่างๆ

**ตัวอย่าง 1.9.10**
จงเขียนโปรแกรมเพื่อหาค่า $x,y,z\in\mathrm{Z}^{+}$ ทั้งหมดที่สอดคล้องกับสมการ
$$x^2+y^2=z^2$$ โดยที่ $1 \leq x, y, z \leq n$ เมื่อ $n\in\mathrm{Z}^{+}$

ตัวอย่างโปรแกรมเป็นดังนี้

In [ ]:
print('This program is used to search integer x,y,z that x^2+y^2=z^2, 1<=x,y,z<=n')
print('where n is positive integer.')
n=int(input('Input n = '))
print('สำหรับ n = {} จะได้ค่า x,y,z ดังนี้'.format(n))
count = 0
for x in range(1,n+1):
  for y in range(1,n+1):
    for z in range(1,n+1):
     if x**2+y**2==z**2:
        count += 1 #count = count + 1
        print('{}. x = {}, y = {}, z = {}'.format(count,x,y,z))
if count==0:
  print('    >>ไม่มี x,y,z ที่สอดคล้อง<<')

This program is used to search integer x,y,z that x^2+y^2=z^2, 1<=x,y,z<=n
where n is positive integer.
Input n = 100
สำหรับ n = 100 จะได้ค่า x,y,z ดังนี้
1. x = 3, y = 4, z = 5
2. x = 4, y = 3, z = 5
3. x = 5, y = 12, z = 13
4. x = 6, y = 8, z = 10
5. x = 7, y = 24, z = 25
6. x = 8, y = 6, z = 10
7. x = 8, y = 15, z = 17
8. x = 9, y = 12, z = 15
9. x = 9, y = 40, z = 41
10. x = 10, y = 24, z = 26
11. x = 11, y = 60, z = 61
12. x = 12, y = 5, z = 13
13. x = 12, y = 9, z = 15
14. x = 12, y = 16, z = 20
15. x = 12, y = 35, z = 37
16. x = 13, y = 84, z = 85
17. x = 14, y = 48, z = 50
18. x = 15, y = 8, z = 17
19. x = 15, y = 20, z = 25
20. x = 15, y = 36, z = 39
21. x = 16, y = 12, z = 20
22. x = 16, y = 30, z = 34
23. x = 16, y = 63, z = 65
24. x = 18, y = 24, z = 30
25. x = 18, y = 80, z = 82
26. x = 20, y = 15, z = 25
27. x = 20, y = 21, z = 29
28. x = 20, y = 48, z = 52
29. x = 21, y = 20, z = 29
30. x = 21, y = 28, z = 35
31. x = 21, y = 72, z = 75
32. x = 24, y = 7, z = 25
33. x = 2

**ตัวอย่าง 1.9.11**
จงเขียนโปรแกรมให้มีการทำงานดังนี้
1. ป้อนค่าจำนวนแถวและหลักของเมทริกซ์ $A$
2. ป้อนค่าจุดปลายของช่วง $I=[a,b]$
3.  สร้างเมทริกซ์ $A = [a_{ij}]_{m\times n}$ โดยที่ $a_{ij}$ แต่ละตัวเป็นจำนวนที่ได้จากการสุ่มแบบเอกรูป(uniform)ในช่วง $[a,b]$
3. นับจำนวนสมาชิกที่มีค่ามากกว่า $0$ สมากชิกที่มีค่าเท่ากับ $0$ และสมาชิกที่มีค่าน้อยกว่า $0$ จากนั้นแสดงจำนวนที่นับได้แต่ละค่า

In [80]:
import math
np.random.seed(42)
c = 5
r = 5
a , b = -2,2
Mat = a+(b -a)*np.random.rand(c,r)
m = 0
e = 0
l = 0
for i in Mat:
  for j in i:
    if j > 0:
      m+=1
    elif j < 0:
      l+=1
    else :
      e+=1
print(m , e , l)
Mat

10 0 15


array([[-0.50183952,  1.80285723,  0.92797577,  0.39463394, -1.37592544],
       [-1.37602192, -1.76766555,  1.46470458,  0.40446005,  0.83229031],
       [-1.91766202,  1.87963941,  1.32977056, -1.15064356, -1.27270013],
       [-1.26638196, -0.78303103,  0.09902573, -0.27221993, -0.83508344],
       [ 0.44741158, -1.44202456, -0.83142141, -0.53455263, -0.17572006]])

ตัวอย่างโปรแกรมเป็นดังนี้

In [83]:
m=5
n=5
a=-2
b=2
np.random.seed(42)
A=a+(b-a)*np.random.rand(m,n)
print('The generated matrix is A = ')
print(A)
count1=0
count2=0
count3=0
for i in range(m):
  for j in range(n):
    if A[i,j]<0:
      count1+=1
    elif A[i,j]==0:
      count2+=1
    else:
      count3+=1
print('Results of counting member in A:')
print('-Number of members of A that less than zero is {} member(s).'.format(count1))
print('-Number of members of A that equal to zero is {} member(s).'.format(count2))
print('-Number of members of A that greater than zero is {} member(s).'.format(count3))

The generated matrix is A = 
[[-0.50183952  1.80285723  0.92797577  0.39463394 -1.37592544]
 [-1.37602192 -1.76766555  1.46470458  0.40446005  0.83229031]
 [-1.91766202  1.87963941  1.32977056 -1.15064356 -1.27270013]
 [-1.26638196 -0.78303103  0.09902573 -0.27221993 -0.83508344]
 [ 0.44741158 -1.44202456 -0.83142141 -0.53455263 -0.17572006]]
Results of counting member in A:
-Number of members of A that less than zero is 15 member(s).
-Number of members of A that equal to zero is 0 member(s).
-Number of members of A that greater than zero is 10 member(s).


# เอกสารอ้างอิง
1. Python Language. https://www.python.org
2. lambda function: http://marcuscode.com/lang/python/lambda-functions
3. Generation: https://en.wikipedia.org/wiki/Generation#:~:text=A%20generation%20refers%20to%20all,and%20begin%20to%20have%20children.%22
4. The 100 most expensive football transfers of all time: https://www.goal.com/en/news/100-most-expensive-football-transfers-all-time/ikr3oojohla51fh9adq3qkwpu


<img src = 'https://drive.google.com/uc?id=18qUXmnQK3FIPfMCm8m0aKf1Saam6ezdJ'>

<img src = 'https://drive.google.com/uc?id=192V5NZG8GXDFzYQIxTRJCSmiBUkc2xys'>